;;; herdr-tests.el --- Tests for herdr.el -*- lexical-binding: t; -*-

;;; Commentary:

;; Run with:
;;   emacs -Q --batch -L . -l herdr-tests.el -f ert-run-tests-batch-and-exit
;;
;; The socket tests run against a fake server, so no herdr install is needed.
;; Tests that need a real server skip themselves when none answers.

;;; Code:

(require 'ert)
(require 'herdr)
(require 'herdr-api)
(require 'herdr-agent)

(defvar herdr-tests--socket-dir nil)
(defvar ghostel-mode-hook)
(defvar ghostel-exit-functions)
(defvar ghostel--term)

(defun herdr-tests--start-server (handler)
  "Start a fake herdr API server answering with HANDLER.
HANDLER receives the decoded request alist and returns the response
alist.  Returns the socket path."
  (setq herdr-tests--socket-dir (make-temp-file "herdr-test" t))
  (let ((path (expand-file-name "herdr.sock" herdr-tests--socket-dir)))
    (make-network-process
     :name "herdr-test-server" :server t :family 'local :service path
     :coding 'utf-8-unix :noquery t
     :filter (lambda (proc chunk)
               (let ((request (json-parse-string
                               (string-trim-right chunk)
                               :object-type 'alist :array-type 'list
                               :null-object :null :false-object :false)))
                 (process-send-string
                  proc (concat (json-serialize (funcall handler request)) "\n")))))
    path))

(defun herdr-tests--teardown ()
  "Stop fake servers and remove their socket directory."
  (dolist (proc (process-list))
    (when (string-prefix-p "herdr-test-server" (process-name proc))
      (delete-process proc)))
  (when (and herdr-tests--socket-dir (file-directory-p herdr-tests--socket-dir))
    (delete-directory herdr-tests--socket-dir t))
  (setq herdr-tests--socket-dir nil))

(ert-deftest herdr-socket-file-defaults-to-config-dir ()
  (let ((process-environment (cons "XDG_CONFIG_HOME=/xdg" process-environment))
        (herdr-socket-path nil)
        (herdr-session nil))
    (should (equal (herdr-socket-file) "/xdg/herdr/herdr.sock"))
    (let ((herdr-socket-path "/tmp/other.sock"))
      (should (equal (herdr-socket-file) "/tmp/other.sock")))))

(ert-deftest herdr-attach-command-shape ()
  (let ((herdr-executable "herdr")
        (herdr-socket-path nil)
        (herdr-session 'shared))
    (should (equal (herdr-attach-command "term_1")
                   '("herdr" "--session" "default" "terminal" "attach" "term_1")))
    (should (equal (herdr-attach-command "term_1" t)
                   '("herdr" "--session" "default" "terminal" "attach" "term_1" "--takeover")))
    (let ((herdr-session "agents"))
      (should (equal (herdr-attach-command "term_1")
                     '("herdr" "--session" "agents" "terminal" "attach" "term_1"))))
    (let ((herdr-session "agents")
          (herdr-socket-path "/tmp/probe/herdr.sock"))
      (should (equal (herdr-attach-command "term_1")
                     '("herdr" "--session" "agents" "terminal" "attach" "term_1"))))))

(ert-deftest herdr-request-returns-result ()
  (unwind-protect
      (let* ((requests nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (request)
                 (push request requests)
                 `((id . ,(alist-get 'id request))
                   (result . ((type . "pong") (protocol . 17))))))))
        (should (equal (alist-get 'protocol (herdr-request "ping")) 17))
        (should (equal (alist-get 'method (car requests)) "ping"))
        (should (herdr-available-p)))
    (herdr-tests--teardown)))

(ert-deftest herdr-request-sends-params ()
  (unwind-protect
      (let* ((failure nil)
             (requests nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (request)
                 (push request requests)
                 `((id . ,(alist-get 'id request))
                   (result . ,(if (equal (alist-get 'method request) "agent.get")
                                  '((agent . ((terminal_id . "term-manage")
                                              (pane_id . "w1:p-manage"))))
                                '((type . "ok")))))))))
        (herdr-request "pane.send_text" '((pane_id . "w1:p1") (text . "hi\n")))
        (condition-case error
            (dolist (kind '("claude" "pi" "codex"))
              (herdr-api-agent-start kind (concat kind "-review") (concat kind ":pane")
                                     :args '("--continue")))
          (error (setq failure error)))
        (should-not failure)
        (require 'herdr-agent)
        (herdr-agent-stop "term-manage")
        (setq requests (nreverse requests))
        (should (equal (mapcar (lambda (request) (alist-get 'method request)) requests)
                       '("pane.send_text" "agent.start" "agent.start" "agent.start"
                         "agent.get" "pane.close")))
        (should (equal (alist-get 'params (nth 0 requests))
                       '((pane_id . "w1:p1") (text . "hi\n"))))
        (should (equal (alist-get 'params (nth 1 requests))
                       '((kind . "claude") (name . "claude-review")
                         (pane_id . "claude:pane") (args . ("--continue")))))
        (should (equal (alist-get 'params (nth 2 requests))
                       '((kind . "pi") (name . "pi-review")
                         (pane_id . "pi:pane") (args . ("--continue")))))
        (should (equal (alist-get 'params (nth 3 requests))
                       '((kind . "codex") (name . "codex-review")
                         (pane_id . "codex:pane") (args . ("--continue")))))
        (should (equal (alist-get 'params (nth 4 requests))
                       '((target . "term-manage"))))
        (should (equal (alist-get 'params (nth 5 requests))
                       '((pane_id . "w1:p-manage")))))
    (herdr-tests--teardown)))

(ert-deftest herdr-request-signals-api-errors ()
  (unwind-protect
      (let ((herdr-socket-path
             (herdr-tests--start-server
              (lambda (request)
                `((id . ,(alist-get 'id request))
                  (error . ((code . "agent_not_found") (message . "nope"))))))))
        (let ((err (should-error (herdr-request "agent.get" '((target . "x")))
                                 :type 'herdr-api-error)))
          (should (equal (cadr err) "agent_not_found"))))
    (herdr-tests--teardown)))

(ert-deftest herdr-request-without-socket-signals ()
  (let ((herdr-socket-path "/nonexistent/herdr.sock"))
    (should-error (herdr-request "ping") :type 'herdr-error)
    (should-not (herdr-available-p))))

(ert-deftest herdr-subscribe-delivers-event-data-not-the-event-kind ()
  (unwind-protect
      (let* ((data '((pane_id . "w1:t1:p1") (terminal_id . "term-1")))
             (received nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (_request)
                 `((event . "pane.updated") (data . ,data))))))
        (herdr-subscribe '("pane.updated") (lambda (event) (setq received event)))
        (accept-process-output nil 0.05)
        (should (equal received data)))
    (herdr-tests--teardown)))

(ert-deftest herdr-api-tab-create-encodes-env-and-focus ()
  (unwind-protect
      (let* ((seen nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (request)
                 (setq seen (alist-get 'params request))
                 `((id . ,(alist-get 'id request))
                   (result . ((type . "tab_created"))))))))
        (herdr-api-tab-create :cwd "/tmp" :label "claude-x" :focus :false
                              :env '((CLAUDE_CODE_SSE_PORT . "4711")))
        (should (equal (alist-get 'label seen) "claude-x"))
        (should (equal (alist-get 'CLAUDE_CODE_SSE_PORT (alist-get 'env seen)) "4711"))
        (should (eq (alist-get 'focus seen) :false)))
    (herdr-tests--teardown)))

(ert-deftest herdr-open-tab-opens-a-workspace-in-an-empty-session ()
  (unwind-protect
      (let* ((calls nil)
             (workspaces nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (request)
                 (push (cons (alist-get 'method request) (alist-get 'params request))
                       calls)
                 `((id . ,(alist-get 'id request))
                   (result . ((type . "ok")
                              (tab . ((tab_id . "w1:t1")))
                              (workspaces . ,(or workspaces [])))))))))
        (herdr-open-tab :cwd "/tmp" :label "first")
        (should (equal (mapcar #'car (reverse calls))
                       '("workspace.list" "workspace.create" "tab.rename")))
        (should (equal (cdr (assq 'label (cdr (nth 1 (reverse calls))))) "first"))
        (setq calls nil)
        (setq workspaces (vector '((workspace_id . "w1") (label . "app"))))
        (herdr-open-tab :cwd "/tmp" :label "second")
        (should (equal (caar calls) "tab.create"))
        (herdr-open-tab :cwd "/tmp" :label "third" :workspace "app")
        (should (equal (cdr (assq 'workspace_id (cdar calls))) "w1")))
    (herdr-tests--teardown)))

(ert-deftest herdr-open-tab-creates-a-missing-workspace-and-names-its-tab ()
  (unwind-protect
      (let* ((calls nil)
             (rename-fault nil)
             (close-fault nil)
             (herdr-socket-path
              (herdr-tests--start-server
               (lambda (request)
                 (push (cons (alist-get 'method request) (alist-get 'params request))
                       calls)
                 (let ((id (alist-get 'id request)))
                   (if (or (and rename-fault
                                (equal (alist-get 'method request) "tab.rename"))
                           (and close-fault
                                (equal (alist-get 'method request) "workspace.close")))
                       (progn
                         (if (equal (alist-get 'method request) "tab.rename")
                             (setq rename-fault nil)
                           (setq close-fault nil))
                         `((id . ,id)
                           (error . ((code . "topology_transition_failed")
                                     (message . "topology transition failed")))))
                     `((id . ,id)
                       (result . ((type . "ok")
                                  (tab . ((tab_id . "w2:t1")))
                                  (workspaces . ,(vector '((workspace_id . "w1")
                                                           (label . "other")))))))))))))
        (herdr-open-tab :cwd "/tmp" :label "feat-x" :workspace "app")
        (let ((methods (mapcar #'car (reverse calls))))
          (should (equal methods '("workspace.list" "workspace.create" "tab.rename"))))
        (should (equal (cdr (assq 'label (cdr (nth 1 (reverse calls))))) "app"))
        (should (equal (cdr (assq 'label (cdar calls))) "feat-x"))
        (should (equal (cdr (assq 'tab_id (cdar calls))) "w2:t1"))
        (setq calls nil
              rename-fault t)
        (should-error (herdr-open-tab :cwd "/tmp" :label "retry" :workspace "app")
                      :type 'herdr-api-error)
        (should (equal (mapcar #'car (reverse calls))
                       '("workspace.list" "workspace.create" "tab.rename"
                         "workspace.close")))
        (setq calls nil)
        (herdr-open-tab :cwd "/tmp" :label "retry" :workspace "app")
        (should (equal (mapcar #'car (reverse calls))
                       '("workspace.list" "workspace.create" "tab.rename"))))
    (herdr-tests--teardown)))

(ert-deftest herdr-default-buffer-name-leads-with-project-and-branch ()
  (let* ((root (make-temp-file "herdr-name" t))
         (repo (expand-file-name "app" root))
         (worktree (expand-file-name "app-wt" root))
         (name (file-name-nondirectory root)))
    (make-directory repo)
    (unwind-protect
        (let ((default-directory repo))
          (should (equal (herdr-default-buffer-name "claude") "*herdr: claude*"))
          (should (equal (herdr-default-buffer-name "claude" root)
                         (format "*herdr: %s claude*" name)))
          (should (zerop (call-process "git" nil nil nil "init" "-q" "-b" "topic/x")))
          (should (equal (herdr-directory-branch repo) "topic/x"))
          (should (equal (herdr-default-buffer-name "claude" (file-name-as-directory repo))
                         "*herdr: app@topic/x claude*"))
          (should (zerop (call-process "git" nil nil nil "-c" "user.name=t"
                                       "-c" "user.email=t@t" "commit" "-q"
                                       "--allow-empty" "-m" "init")))
          (should (zerop (call-process "git" nil nil nil "worktree" "add" "-q"
                                       "-b" "feat/y" worktree)))
          (should (equal (herdr-default-buffer-name "claude" worktree)
                         "*herdr: app@feat/y claude*"))
          (should (equal (herdr-directory-branch (expand-file-name "src" worktree))
                         nil))
          (make-directory (expand-file-name "src" worktree))
          (should (equal (herdr-directory-branch (expand-file-name "src" worktree))
                         "feat/y"))
          (should (zerop (call-process "git" nil nil nil "checkout" "-q" "--detach")))
          (let ((detached (herdr-directory-branch repo)))
            (should (string-match-p "\\`[0-9a-f]\\{7\\}\\'" detached))
            (should (equal detached
                           (herdr--git-line repo "rev-parse" "--short=7" "HEAD"))))
          (should-not (herdr-directory-branch root)))
      (delete-directory root t))))

(ert-deftest herdr-buffer-names-make-room-for-repeated-labels ()
  (let ((first (get-buffer-create "*herdr: 1*"))
        (second nil))
    (unwind-protect
        (progn
          (start-process "herdr-test-sleep" first "sleep" "30")
          (herdr-claim-buffer first "term_a")
          (should (equal (herdr--free-buffer-name "1" "term_b") "*herdr: 1<2>*"))
          (should-error (herdr--free-buffer-name "1" "term_a") :type 'user-error)
          (setq second (get-buffer-create "*herdr: 1<2>*"))
          (start-process "herdr-test-sleep-2" second "sleep" "30")
          (herdr-claim-buffer second "term_b")
          (should (equal (herdr--free-buffer-name "1" "term_c") "*herdr: 1<3>*")))
      (dolist (buffer (list first second))
        (when (buffer-live-p buffer)
          (when-let* ((process (get-buffer-process buffer))) (delete-process process))
          (kill-buffer buffer))))))

(ert-deftest herdr-session-layout-groups-entries-by-workspace ()
  (cl-letf (((symbol-function 'herdr-workspaces)
             (lambda () '(((workspace_id . "w1") (label . "app"))
                          ((workspace_id . "w2") (label . "empty")))))
            ((symbol-function 'herdr-tabs)
             (lambda () '(((tab_id . "w1:t1") (label . "feat-a")))))
            ((symbol-function 'herdr-agents)
             (lambda () '(((workspace_id . "w1") (tab_id . "w1:t1") (terminal_id . "t1"))
                          ((workspace_id . "w1") (terminal_id . "t2")))))
            ((symbol-function 'herdr-panes)
             (lambda () '(((workspace_id . "w1") (terminal_id . "t1"))
                          ((workspace_id . "w2") (terminal_id . "t3"))))))
    (let ((layout (herdr-session-layout)))
      (should (= (length layout) 1))
      (should (equal (alist-get 'label (caar layout)) "app"))
      (should (= (length (cdar layout)) 2))
      (should (equal (alist-get 'kind (car (cdar layout))) "herdr"))
      (should (equal (herdr--entry-label (car (cdar layout))) "feat-a")))
    (should (= (length (herdr-session-layout t)) 2))))

(ert-deftest herdr-attach-session-opens-workspaces-and-skips-attached ()
  (let* ((opened nil)
         (attached nil)
         (herdr-attach-session-workspace-policy 'mirror)
         (herdr-workspace-open-function
          (lambda (workspace directory)
            (push (cons (alist-get 'label workspace) directory) opened)
            "app"))
         (herdr-attach-takeover t))
    (cl-letf (((symbol-function 'herdr-available-p) (lambda () t))
              ((symbol-function 'herdr-session-layout)
               (lambda (&optional _all)
                 '((((workspace_id . "w1") (label . "app"))
                    ((terminal_id . "t1") (cwd . "/src/app"))
                    ((terminal_id . "t2") (cwd . "/src/app"))))))
              ((symbol-function 'herdr-terminal-buffer)
               (lambda (terminal-id) (equal terminal-id "t2")))
              ((symbol-function 'herdr-attach-entry)
               (lambda (entry)
                 (push (list (alist-get 'terminal_id entry)
                             herdr-attach-takeover
                             herdr-attach-session-workspace)
                       attached)
                 'buffer)))
      (should (equal (herdr-attach-session "work") '(buffer)))
      (should (equal opened '(("app" . "/src/app"))))
      (should (equal attached '(("t1" nil "app"))))
      (should-not herdr-attach-session-workspace))))

(ert-deftest herdr-attach-session-merges-groups-by-editor-workspace-label ()
  (let* ((herdr-attach-session-workspace-policy 'merge)
         (herdr-workspace-label-function
          (lambda (directory)
            (if (string-prefix-p "/src/app" directory) "app" "other")))
         opened attached
         (herdr-workspace-open-function
          (lambda (workspace directory)
            (push (list (alist-get 'workspace_id workspace) directory) opened)
            (herdr-workspace-label directory))))
    (cl-letf (((symbol-function 'herdr-available-p) (lambda () t))
              ((symbol-function 'herdr-session-layout)
               (lambda (&optional _all)
                 '((((workspace_id . "w1"))
                    ((terminal_id . "t1") (cwd . "/src/app")))
                   (((workspace_id . "w2"))
                    ((terminal_id . "t2")
                     (cwd . "/src/app/.worktrees/fix")))
                   (((workspace_id . "w3"))
                    ((terminal_id . "t3") (cwd . "/src/other"))))))
              ((symbol-function 'herdr-terminal-buffer) (lambda (&rest _) nil))
              ((symbol-function 'herdr-attach-entry)
               (lambda (entry)
                 (push (cons (alist-get 'terminal_id entry)
                             herdr-attach-session-workspace)
                       attached)
                 'buffer)))
      (should (= (length (herdr-attach-session "work")) 3))
      (should (equal (nreverse opened)
                     '(("w1" "/src/app") ("w3" "/src/other"))))
      (should (equal (nreverse attached)
                     '(("t1" . "app") ("t2" . "app")
                       ("t3" . "other"))))
      (should-not herdr-attach-session-workspace))))

(ert-deftest herdr-entry-directory-follows-the-running-process ()
  (should (equal (herdr-entry-directory
                  '((cwd . "/src/app") (foreground_cwd . "/src/app/.worktrees/x")))
                 "/src/app/.worktrees/x"))
  (should (equal (herdr-entry-directory '((cwd . "/src/app"))) "/src/app"))
  (should (equal (herdr-entry-directory
                  '((cwd . "/src/app") (foreground_cwd . "")))
                 "/src/app"))
  (should-not (herdr-entry-directory '((pane_id . "%1")))))

(ert-deftest herdr-attach-keeps-a-buffer-out-of-a-directory-that-is-gone ()
  (let* ((root (file-truename (make-temp-file "herdr-live-directory" t)))
         (gone (expand-file-name "removed" root))
         (buffers nil)
         (messages nil))
    (unwind-protect
        (cl-letf (((symbol-function 'herdr--terminal-exec)
                   (lambda (buffer _program _arguments) buffer))
                  ((symbol-function 'herdr-attach-command)
                   (lambda (&rest _) '("herdr" "attach")))
                  ((symbol-function 'message)
                   (lambda (format &rest arguments)
                     (push (apply #'format format arguments) messages))))
          (should (equal (herdr-live-directory root) (file-name-as-directory root)))
          (should-not (herdr-live-directory gone))
          (should-not (herdr-live-directory ""))
          (should-not (herdr-live-directory nil))
          (let ((default-directory (file-name-as-directory root)))
            (push (herdr-attach-terminal "term_live" :label "live" :directory root)
                  buffers)
            (should (equal (buffer-local-value 'default-directory (car buffers))
                           (file-name-as-directory root)))
            (should-not messages)
            (push (herdr-attach-terminal "term_gone" :label "gone" :directory gone)
                  buffers)
            (should (equal (buffer-local-value 'default-directory (car buffers))
                           (file-name-as-directory root)))
            (should (equal (length messages) 1))
            (should (string-match-p "which is gone" (car messages)))))
      (dolist (buffer buffers)
        (when (buffer-live-p buffer) (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest herdr-repository-root-folds-a-worktree-into-its-checkout ()
  (unless (executable-find "git")
    (ert-skip "git is not installed"))
  (let* ((root (file-truename (make-temp-file "herdr-repository" t)))
         (main (expand-file-name "main" root))
         (worktree (expand-file-name "side" root))
         (herdr--repository-roots (make-hash-table :test #'equal)))
    (unwind-protect
        (progn
          (make-directory main)
          (let ((default-directory (file-name-as-directory main)))
            (should (eq 0 (call-process "git" nil nil nil "init" "--quiet")))
            (call-process "git" nil nil nil "config" "user.email" "t@example.com")
            (call-process "git" nil nil nil "config" "user.name" "Herdr Test")
            (with-temp-file (expand-file-name "a" main) (insert "a\n"))
            (call-process "git" nil nil nil "add" "a")
            (call-process "git" nil nil nil "commit" "--quiet" "-m" "one")
            (should (eq 0 (call-process "git" nil nil nil "worktree" "add"
                                        "--quiet" "-b" "side" worktree))))
          (should (equal (herdr-repository-root main) main))
          (should (equal (herdr-repository-root worktree) main))
          (should (equal (herdr-directory-project worktree) "main"))
          (should-not (herdr-repository-root root))
          (should-not (herdr-repository-root (expand-file-name "gone" root)))
          (should (= (hash-table-count herdr--repository-roots) 3)))
      (delete-directory root t))))

(ert-deftest herdr-recent-first-leads-with-what-was-reached-for ()
  (let* ((one '((server_key . "/s") (terminal_id . "t1") (name . "one")))
         (two '((server_key . "/s") (terminal_id . "t2") (name . "two")))
         (three '((server_key . "/s") (terminal_id . "t3") (name . "three")))
         (entries (list one two three))
         (herdr--recent-session-targets nil))
    (should (equal (herdr-recent-first entries) entries))
    (setq herdr--recent-session-targets
          '(("/s" . "t3") ("/s" . "gone") ("/s" . "t1")))
    (should (equal (mapcar (lambda (entry) (alist-get 'name entry))
                           (herdr-recent-first entries))
                   '("three" "one" "two")))
    (should-not (herdr-recent-first nil))))

(ert-deftest herdr-read-entry-keeps-the-order-it-was-handed ()
  (let ((entries (list '((name . "zeta") (terminal_id . "t1") (server_key . "/s"))
                       '((name . "alpha") (terminal_id . "t2") (server_key . "/s"))))
        metadata)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt table &rest _)
                 (setq metadata (cdr (funcall table "" nil 'metadata)))
                 "zeta")))
      (herdr-read-entry "Pick: " entries))
    (should (eq (alist-get 'display-sort-function metadata) #'identity))
    (should (eq (alist-get 'cycle-sort-function metadata) #'identity))))

(ert-deftest herdr-attach-pane-offers-only-panes-running-no-agent ()
  (let (offered)
    (cl-letf (((symbol-function 'herdr-panes)
               (lambda ()
                 '(((pane_id . "%1") (agent . "claude") (terminal_id . "t1"))
                   ((pane_id . "%9") (terminal_id . "t9")))))
              ((symbol-function 'herdr-read-entry)
               (lambda (_prompt entries &rest _)
                 (setq offered entries)
                 (car entries)))
              ((symbol-function 'herdr-attach-entry) #'identity))
      (call-interactively #'herdr-attach-pane))
    (should (equal (mapcar (lambda (entry) (alist-get 'pane_id entry)) offered)
                   '("%9")))))

(ert-deftest herdr-workspace-label-defaults-to-the-directory-name ()
  (let ((herdr-workspace-label-function #'herdr-default-workspace-label))
    (should (equal (herdr-workspace-label "/src/app/") "app"))
    (should (equal (herdr-workspace-label "/src/app/.worktrees/feat-x") "feat-x"))))

(ert-deftest herdr-current-workspace-label-defaults-to-the-project-root ()
  (let ((buffer-file-name "/src/app/lib/example.el")
        (herdr-project-root-function
         (lambda (directory)
           (and (string-prefix-p "/src/app/" directory) "/src/app/")))
        (herdr-workspace-label-function #'herdr-default-workspace-label))
    (should (equal (herdr-default-current-workspace-label) "app"))))

(ert-deftest herdr-display-buffer-uses-a-side-window ()
  (let ((buffer (get-buffer-create "*herdr: probe*"))
        (herdr-use-side-window t)
        (herdr-window-side 'right)
        (herdr-window-width 20)
        (herdr-display-buffer-action nil))
    (unwind-protect
        (let ((window (herdr-display-buffer buffer)))
          (should window)
          (should (eq (window-parameter window 'window-side) 'right))
          (should (equal (window-parameter window 'window-slot)
                         (buffer-local-value 'herdr--window-slot buffer)))
          (should (>= (buffer-local-value 'herdr--window-slot buffer)
                      herdr-window-slot-base))
          (should (eq (window-dedicated-p window) 'side)))
      (kill-buffer buffer))))

(ert-deftest herdr-killing-an-attached-terminal-can-find-its-window-a-buffer ()
  "A window dedicated with t rather than `side' makes
`switch-to-prev-buffer' an error, which is what kill-buffer advice that
looks for a replacement buffer runs into."
  (let ((buffer (generate-new-buffer "*herdr: probe term_dedicated*"))
        (herdr-use-side-window t)
        (herdr-window-side 'right)
        (herdr-display-buffer-action nil))
    (unwind-protect
        (let ((window (herdr-display-buffer buffer)))
          (should-not (eq (window-dedicated-p window) t))
          (with-selected-window window
            (should-not (condition-case err
                            (progn (switch-to-prev-buffer nil t) nil)
                          (error err)))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest herdr-ghostel-focus-event-drops-focus-loss-for-attached-terminals ()
  (let ((buffer (generate-new-buffer " *herdr focus*"))
        (herdr-report-focus-loss nil)
        calls)
    (unwind-protect
        (with-current-buffer buffer
          (setq-local ghostel--focus-state t)
          (cl-flet ((native (term gained) (push (list term gained) calls) t))
            (should (herdr--ghostel-focus-event #'native 'term nil))
            (should (equal calls '((term nil))))
            (setq calls nil)
            (setq herdr-terminal-id "term-1")
            (setq-local ghostel--focus-state t)
            (should-not (herdr--ghostel-focus-event #'native 'term nil))
            (should-not calls)
            (should-not ghostel--focus-state)
            (should (herdr--ghostel-focus-event #'native 'term t))
            (should (equal calls '((term t))))
            (let ((herdr-report-focus-loss t))
              (should (herdr--ghostel-focus-event #'native 'term nil)))
            (should (equal (car calls) '(term nil)))))
      (kill-buffer buffer))))

(ert-deftest herdr-display-buffer-gives-each-terminal-its-own-slot ()
  (let ((first (get-buffer-create "*herdr: one*"))
        (second (get-buffer-create "*herdr: two*"))
        (herdr-window-width 20))
    (unwind-protect
        (progn
          (herdr-display-buffer first)
          (herdr-display-buffer second)
          (should-not (equal (buffer-local-value 'herdr--window-slot first)
                             (buffer-local-value 'herdr--window-slot second))))
      (kill-buffer first)
      (kill-buffer second))))

(ert-deftest herdr-display-buffer-returns-a-window-without-side-windows ()
  (let ((buffer (get-buffer-create "*herdr: plain*"))
        (herdr-use-side-window nil)
        (herdr-display-buffer-action nil))
    (unwind-protect
        (let ((window (herdr-display-buffer buffer)))
          (should (windowp window))
          (should (eq (window-buffer window) buffer))
          (should-not (window-parameter window 'window-side)))
      (kill-buffer buffer))))

(ert-deftest herdr-display-buffer-action-overrides-the-side-window ()
  (let ((buffer (get-buffer-create "*herdr: override*"))
        (herdr-display-buffer-action '(display-buffer-same-window)))
    (unwind-protect
        (should-not (window-parameter (herdr-display-buffer buffer) 'window-side))
      (kill-buffer buffer))))

(ert-deftest herdr-claim-buffer-marks-and-announces-the-buffer ()
  (let ((buffer (get-buffer-create "*herdr: claimed*"))
        (announced nil))
    (unwind-protect
        (let ((herdr-buffer-functions (list (lambda (b) (push b announced)))))
          (should (eq (herdr-claim-buffer buffer "term_claim") buffer))
          (should (equal (buffer-local-value 'herdr-terminal-id buffer) "term_claim"))
          (should (equal announced (list buffer))))
      (kill-buffer buffer))))

(ert-deftest herdr-terminal-buffer-needs-a-live-process ()
  (let ((buffer (get-buffer-create "*herdr: lookup*")))
    (unwind-protect
        (progn
          (herdr-claim-buffer buffer "term_lookup")
          (should-not (herdr-terminal-buffer "term_lookup"))
          (start-process "herdr-test-sleep" buffer "sleep" "30")
          (should (eq (herdr-terminal-buffer "term_lookup") buffer))
          (should-not (herdr-terminal-buffer "term_missing")))
      (when-let* ((process (get-buffer-process buffer))) (delete-process process))
      (kill-buffer buffer))))

(ert-deftest herdr-sessions-dedups-terminals-preferring-live-buffers ()
  (let ((buffer (get-buffer-create "*herdr: session*")))
    (unwind-protect
        (let* ((bare '((kind . "herdr") (terminal_id . "term_dup") (agent . "claude")
                       (terminal_title_stripped . "bare")))
               (rich `((kind . "editor") (terminal_id . "term_dup")
                       (label . "rich") (buffer . ,buffer)))
               (other '((kind . "herdr") (terminal_id . "term_other") (agent . "codex")))
               (herdr-session-functions
                (list (lambda () (list bare other)) (lambda () (list rich)))))
          (cl-letf (((symbol-function 'herdr-all-sessions) (lambda () '(shared)))
                    ((symbol-function 'herdr-available-p) (lambda () t)))
            (let ((sessions (herdr-sessions)))
              (should (= (length sessions) 2))
              (should (equal (herdr--entry-label (car sessions)) "rich"))
              (should (equal (alist-get 'terminal_id (cadr sessions)) "term_other")))))
      (kill-buffer buffer))))

(ert-deftest herdr-visit-shows-a-live-buffer-instead-of-attaching ()
  (let ((buffer (get-buffer-create "*herdr: visit*"))
        (herdr--recent-session-targets nil)
        (popped nil))
    (unwind-protect
        (cl-letf (((symbol-function 'pop-to-buffer) (lambda (b &rest _) (setq popped b)))
                  ((symbol-function 'herdr-attach-entry)
                   (lambda (&rest _) (error "Should not attach an attached session"))))
          (should (eq (herdr-visit `((buffer . ,buffer)
                                     (agent . "claude")
                                     (server_key . "/servers/a.sock")
                                     (terminal_id . "shared")))
                      buffer))
          (should (eq popped buffer))
          (should (equal herdr--recent-session-targets
                         '(("/servers/a.sock" . "shared")))))
      (kill-buffer buffer))))

(ert-deftest herdr-visit-attaches-a-session-without-a-buffer ()
  (cl-letf (((symbol-function 'herdr-attach-entry) (lambda (_entry) 'attached)))
    (should (eq (herdr-visit '((terminal_id . "term_cold"))) 'attached))))

(ert-deftest herdr-attach-entry-lets-a-hook-claim-the-entry ()
  (let* ((claimed (get-buffer-create "*herdr: claimed*"))
         (seen nil)
         (herdr-attach-functions
          (list (lambda (entry) (setq seen entry) claimed))))
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-attach-terminal)
                   (lambda (&rest _) (error "Should not attach a terminal"))))
          (should (eq (herdr-attach-entry '((agent . "claude") (terminal_id . "term_1")))
                      claimed))
          (should (equal (alist-get 'terminal_id seen) "term_1")))
      (kill-buffer claimed))))

(ert-deftest herdr-attach-entry-falls-through-to-the-terminal ()
  (let ((herdr-attach-functions (list (lambda (_entry) nil)))
        (attached nil))
    (cl-letf (((symbol-function 'herdr-attach-terminal)
               (lambda (terminal-id &rest _) (setq attached terminal-id) 'buffer)))
      (should (eq (herdr-attach-entry '((agent . "codex") (terminal_id . "term_2")))
                  'buffer))
      (should (equal attached "term_2")))))

(ert-deftest herdr-agent-attachment-runs-the-registered-adapter ()
  (let* ((terminal-id "term-claude")
         (entry `((agent . "claude")
                  (cwd . ,default-directory)
                  (terminal_id . ,terminal-id)
                  (agent_status . "idle")))
         (buffer (generate-new-buffer " *herdr: claude*"))
         (process (start-process "herdr-claude" buffer "sleep" "30"))
         (herdr-agent--adapters nil)
         phases session
         (adapter (lambda (_session phase &optional _context)
                    (push phase phases))))
    (herdr-agent-register-adapter "claude" adapter)
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-attach-terminal)
                   (lambda (&rest _) buffer)))
          (should (eq (herdr-attach-entry entry) buffer))
          (setq session (herdr-agent-find (herdr-server-key) terminal-id))
          (should session)
          (should (equal (nreverse phases) '(:adopted :attached))))
      (when session
        (herdr-agent-detach session))
      (herdr-agent-unregister-adapter "claude" adapter)
      (when (process-live-p process)
        (delete-process process))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))))

(ert-deftest herdr-socket-file-uses-the-session-data-dir ()
  (let ((process-environment (cons "XDG_CONFIG_HOME=/xdg" process-environment))
        (herdr-socket-path nil)
        (herdr-session "work"))
    (should (equal (herdr-socket-file) "/xdg/herdr/sessions/work/herdr.sock"))))

(ert-deftest herdr-session-name-resolves-the-choices ()
  (let ((herdr-emacs-session-name "emacs"))
    (let ((herdr-session 'shared)) (should-not (herdr-session-name)))
    (let ((herdr-session nil)) (should-not (herdr-session-name)))
    (let ((herdr-session 'emacs)) (should (equal (herdr-session-name) "emacs")))
    (let ((herdr-session "agents")) (should (equal (herdr-session-name) "agents")))
    (let ((herdr-session 42)) (should-error (herdr-session-name) :type 'herdr-error))))

(ert-deftest herdr-project-root-asks-projectile-only-when-loaded ()
  (cl-letf (((symbol-function 'projectile-project-root) (lambda (&rest _) "/p/projectile/"))
            ((symbol-function 'project-current) (lambda (&rest _) nil)))
    (should-not (featurep 'projectile))
    (should-not (herdr-project-root "/tmp"))
    (unwind-protect
        (progn
          (provide 'projectile)
          (should (equal (herdr-project-root "/tmp") "/p/projectile/")))
      (setq features (delq 'projectile features)))))

(ert-deftest herdr-session-for-prefers-assignments-over-rules ()
  (let ((herdr-session 'shared)
        (herdr-session-alist '(("/src" . "derived")))
        (herdr-project-sessions '(("/src/work/" . "work")))
        (herdr-project-root-function
         (lambda (&optional directory)
           (when (string-prefix-p "/src/work" (or directory "")) "/src/work/"))))
    (should (equal (herdr-session-for "/src/work/sub") "work"))
    (should (equal (herdr-session-for "/src/other") "derived"))
    (should (eq (herdr-session-for "/elsewhere") 'shared))))

(ert-deftest herdr-project-session-falls-back-to-the-deepest-assignment ()
  (let ((herdr-project-sessions '(("/src/" . "outer") ("/src/app/" . "inner")))
        (herdr-project-root-function (lambda (&rest _) nil)))
    (should (equal (herdr-project-session "/src/app/lib") "inner"))
    (should (equal (herdr-project-session "/src/other") "outer"))
    (should-not (herdr-project-session "/elsewhere")))
  (let ((herdr-project-sessions '(("/src/" . "outer") ("/src/app/" . "inner")))
        (herdr-project-root-function (lambda (&rest _) "/src/")))
    (should (equal (herdr-project-session "/src/app/lib") "outer"))))

(ert-deftest herdr-assign-project-replaces-and-drops ()
  (let ((herdr-project-sessions nil)
        (herdr--stored-assignments (cons herdr-state-file nil)))
    (herdr-assign-project "/tmp/proj" "work" t)
    (should (equal (cdar (herdr-stored-assignments)) "work"))
    (herdr-assign-project "/tmp/proj/" "private" t)
    (should (= (length (herdr-stored-assignments)) 1))
    (should (equal (cdar (herdr-stored-assignments)) "private"))
    (herdr-assign-project "/tmp/proj" nil t)
    (should-not (herdr-stored-assignments))))

(ert-deftest herdr-assignments-survive-a-round-trip-through-the-state-file ()
  (let* ((directory (make-temp-file "herdr-state" t))
         (herdr-state-file (expand-file-name "herdr/project-sessions.eld" directory))
         (herdr-project-sessions nil)
         (herdr--stored-assignments nil))
    (unwind-protect
        (progn
          (herdr-assign-project "/tmp/work" "work")
          (should (file-readable-p herdr-state-file))
          (let ((herdr--stored-assignments nil))
            (should (equal (herdr-stored-assignments) '(("/tmp/work/" . "work"))))
            (should (equal (herdr-project-session "/tmp/work/sub") "work"))))
      (delete-directory directory t))))

(ert-deftest herdr-configured-assignments-win-over-stored-ones ()
  (let ((herdr-project-sessions '(("/tmp/proj/" . "configured")))
        (herdr--stored-assignments (cons herdr-state-file '(("/tmp/proj/" . "stored"))))
        (herdr-project-root-function (lambda (&rest _) "/tmp/proj/")))
    (should (equal (herdr-project-session "/tmp/proj/sub") "configured"))
    (should (equal (herdr-known-sessions) '(shared "configured" "stored")))))

(ert-deftest herdr-stored-assignments-tolerate-a-broken-state-file ()
  (let* ((directory (make-temp-file "herdr-state" t))
         (herdr-state-file (expand-file-name "broken.eld" directory))
         (herdr--stored-assignments nil))
    (unwind-protect
        (progn
          (with-temp-file herdr-state-file (insert "(((("))
          (should-not (herdr-stored-assignments)))
      (delete-directory directory t))))

(ert-deftest herdr-known-sessions-covers-assignments-and-rules ()
  (let ((herdr-session 'shared)
        (herdr-project-sessions '(("/a" . "work")))
        (herdr-session-alist '(("/b" . "private") ("/c" . "work"))))
    (should (equal (herdr-known-sessions) '(shared "work" "private")))))

(ert-deftest herdr-all-sessions-adds-the-servers-only-disk-knows ()
  (let ((herdr-session 'shared)
        (herdr-project-sessions nil)
        (herdr-session-alist '(("/b" . "work"))))
    (cl-letf (((symbol-function 'herdr-available-sessions)
               (lambda () '(shared "work" "build"))))
      (should (equal (herdr-all-sessions) '(shared "work" "build"))))))

(ert-deftest herdr-all-sessions-treats-emacs-and-its-name-as-one ()
  (let ((herdr-session 'emacs)
        (herdr-emacs-session-name "emacs")
        (herdr-project-sessions nil)
        (herdr-session-alist nil))
    (cl-letf (((symbol-function 'herdr-available-sessions)
               (lambda () '(shared "emacs"))))
      (should (equal (herdr-all-sessions) '(emacs shared))))))

(ert-deftest herdr-socket-file-follows-the-session-choice ()
  (let ((process-environment (cons "XDG_CONFIG_HOME=/xdg" process-environment))
        (herdr-socket-path nil)
        (herdr-emacs-session-name "emacs"))
    (let ((herdr-session 'shared))
      (should (equal (herdr-socket-file) "/xdg/herdr/herdr.sock")))
    (let ((herdr-session 'emacs))
      (should (equal (herdr-socket-file) "/xdg/herdr/sessions/emacs/herdr.sock")))))

(ert-deftest herdr-process-environment-points-at-our-socket ()
  (let ((herdr-socket-path "/tmp/probe/herdr.sock"))
    (should (member "HERDR_SOCKET_PATH=/tmp/probe/herdr.sock"
                    (herdr-process-environment)))))

(ert-deftest herdr-terminal-exec-passes-session-across-buffer-local-environments ()
  (with-temp-buffer
    (setq-local process-environment '("HERDR_SOCKET_PATH=/wrong/herdr.sock"))
    (let ((herdr-session 'shared)
          (herdr-socket-path "/also-wrong/herdr.sock")
          (herdr-executable "/some path/herdr")
          seen)
      (cl-letf (((symbol-function 'herdr--terminal-exec-1)
                 (lambda (buffer program args)
                   (with-temp-buffer
                     (setq-local process-environment nil)
                     (setq seen (cons program args)))
                   buffer)))
        (let ((command (herdr-attach-command "term_1" t "build")))
          (herdr--terminal-exec 'buffer (car command) (cdr command)))
        (should (equal seen '("/some path/herdr" "--session" "build"
                              "terminal" "attach" "term_1" "--takeover")))
        (should (equal (getenv "HERDR_SOCKET_PATH") "/wrong/herdr.sock"))))))

(ert-deftest herdr-start-server-if-needed-starts-one-when-missing ()
  (let ((started 0))
    (cl-letf (((symbol-function 'herdr-available-p) (lambda () nil))
              ((symbol-function 'herdr-start-server)
               (lambda () (cl-incf started) t)))
      (let ((herdr-auto-start-server t))
        (should (herdr-start-server-if-needed))
        (should (= started 1)))
      (let ((herdr-auto-start-server nil))
        (should-error (herdr-start-server-if-needed) :type 'herdr-error)
        (should (= started 1)))))
  (cl-letf (((symbol-function 'herdr-available-p) (lambda () t))
            ((symbol-function 'herdr-start-server)
             (lambda () (error "Should not start a second server"))))
    (should (herdr-start-server-if-needed))))

(ert-deftest herdr-start-server-needs-the-executable ()
  (let ((herdr-executable "herdr-that-is-not-installed"))
    (cl-letf (((symbol-function 'call-process-shell-command)
               (lambda (&rest _) (error "Should not run a missing executable"))))
      (should-error (herdr-start-server) :type 'herdr-error))))

(ert-deftest herdr-live-server-answers-ping ()
  (let ((herdr-socket-path nil))
    (unless (herdr-available-p)
      (ert-skip "no herdr server running"))
    (should (alist-get 'protocol (herdr-request "ping")))
    (should (listp (herdr-agents)))))

(ert-deftest herdr-ghostel-error-survives-terminal-cleanup ()
  (let ((buffer (generate-new-buffer " *herdr-failed-attach*"))
        (diagnostics (generate-new-buffer " *herdr-error-test*"))
        (require-feature (symbol-function 'require))
        (ghostel-mode-hook nil)
        (herdr-terminal-backend 'ghostel)
        (create-buffer (symbol-function 'get-buffer-create))
        warnings)
    (unwind-protect
        (cl-letf (((symbol-function 'require)
                   (lambda (feature &rest args)
                     (if (eq feature 'ghostel) t
                       (apply require-feature feature args))))
                  ((symbol-function 'get-buffer-create)
                   (lambda (name &rest args)
                     (if (equal name "*herdr-errors*") diagnostics
                       (apply create-buffer name args))))
                  ((symbol-function 'display-warning)
                   (lambda (_type message &rest _) (push message warnings)))
                  ((symbol-function 'ghostel-exec)
                   (lambda (target &rest _)
                     (with-current-buffer target
                       (kill-all-local-variables)
                       (setq-local ghostel--term 'native)
                       (run-hooks 'ghostel-mode-hook))))
                  ((symbol-function 'ghostel--copy-all-text)
                   (lambda (_term)
                     "herdr: server shut down: terminal attach failed: terminal term-missing not found\n")))
          (with-current-buffer buffer
            (setq herdr-terminal-id "term-missing"
                  herdr-terminal-session "build"
                  herdr-terminal-server-key "/sessions/build/herdr.sock"))
          (herdr--terminal-exec buffer "herdr" nil)
          (with-current-buffer buffer
            (should (memq #'herdr--terminal-exited ghostel-exit-functions))
            (should (= (point-min) (point-max)))
            (run-hook-with-args 'ghostel-exit-functions buffer "finished\n")
            (run-hook-with-args 'ghostel-exit-functions buffer "finished\n"))
          (kill-buffer buffer)
          (should (= 1 (length warnings)))
          (should (string-match-p "build / term-missing" (car warnings)))
          (with-current-buffer diagnostics
            (should buffer-read-only)
            (should (string-match-p "terminal term-missing not found" (buffer-string)))
            (should (string-match-p "/sessions/build/herdr.sock" (buffer-string)))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (kill-buffer diagnostics))))

(ert-deftest herdr-terminal-deliberate-close-and-normal-detach-are-quiet ()
  (with-temp-buffer
    (setq herdr-terminal-id "term-1" herdr-terminal-session "build")
    (setq-local ghostel--term 'native)
    (cl-letf (((symbol-function 'ghostel--copy-all-text) (lambda (_term) nil))
              ((symbol-function 'display-warning)
               (lambda (&rest _) (ert-fail "Unexpected exit warning"))))
      (herdr--terminal-exited (current-buffer) "finished\n")
      (insert "herdr: an earlier error\nherdr: detached from server\n")
      (herdr--terminal-exited (current-buffer) "finished\n")
      (should-not herdr--terminal-error-reported)
      (insert "herdr: server shut down: terminal term-1 exited\n")
      (herdr--terminal-exited (current-buffer) "finished\n")
      (should-not herdr--terminal-error-reported)
      (insert "herdr: server shut down: terminal attach taken over\n")
      (herdr--terminal-closing)
      (herdr--terminal-exited (current-buffer) "deleted\n")
      (should-not herdr--terminal-error-reported))))

(ert-deftest herdr-terminal-reason-keeps-a-fault-and-drops-a-plain-ending ()
  (should-not (herdr--terminal-error-reason
               "herdr: server shut down: terminal term_65ba exited\n"))
  (should-not (herdr--terminal-error-reason "herdr: detached from server\n"))
  (should (equal (herdr--terminal-error-reason
                  "herdr: server shut down: terminal attach taken over\n")
                 "server shut down: terminal attach taken over"))
  (should (equal (herdr--terminal-error-reason
                  "herdr: lost connection to server: broken pipe\n")
                 "lost connection to server: broken pipe"))
  (should-not (herdr--terminal-error-reason
               (concat "herdr: lost connection to server: broken pipe\n"
                       "herdr: server shut down: terminal term_65ba exited\n"))))

(ert-deftest herdr-attach-entry-session-overrides-stale-socket-metadata ()
  (let ((herdr-session 'shared)
        (herdr-socket-path "/wrong/herdr.sock")
        (herdr-attach-functions nil)
        (entry '((terminal_id . "term-1") (session . "build")
                 (server_key . "/wrong/herdr.sock")))
        seen)
    (cl-letf (((symbol-function 'herdr-attach-terminal)
               (lambda (_terminal &rest args) (setq seen args) 'buffer)))
      (herdr-attach-entry entry)
      (should (equal (plist-get seen :session) "build"))
      (herdr-attach-entry entry "review")
      (should (equal (plist-get seen :session) "review"))
      (should (equal (alist-get 'session entry) "build")))))

(ert-deftest herdr-takes-a-harness-preamble-off-a-title-and-nothing-else ()
  (dolist (case '(("π > Notizen für Slides" . "Notizen für Slides")
                  ("π ∴ Slides" . "Slides")
                  ("π ⠋ working now" . "working now")
                  ("π 🌓 moon phase" . "moon phase")
                  ("π | ascii spinner" . "ascii spinner")))
    (should (equal (herdr--undecorated-label (car case)) (cdr case))))
  (dolist (kept '("π Notizen" "π calculation of π" "π" "π >" "◑ peira migration"
                  "plain title" "" "a π b"))
    (should (equal (herdr--undecorated-label kept) kept)))
  (should-not (herdr--undecorated-label nil))
  (should (equal (herdr--undecorated-label 42) 42))
  (let ((herdr-entry-label-decorations '("\\`\\(" "\\`π > ")))
    (should (equal (herdr--undecorated-label "π > kept") "kept"))))

(ert-deftest herdr-leaves-a-named-entry-its-name ()
  (should (equal (herdr--entry-label '((name . "π > mine")
                                       (terminal_title_stripped . "π > other")))
                 "π > mine"))
  (should (equal (herdr--entry-label '((terminal_title_stripped . "π > other")))
                 "other")))

;;;; Buffers following their labels

(defun herdr-tests--terminal-buffer (name terminal given)
  "Return a live buffer NAME showing TERMINAL, named GIVEN by herdr."
  (let ((buffer (generate-new-buffer name)))
    (with-current-buffer buffer
      (setq-local herdr-terminal-id terminal
                  herdr-terminal-server-key "/tmp/a.sock"
                  herdr--buffer-name given))
    (make-process :name "herdr-follow" :buffer buffer
                  :command '("sleep" "30") :noquery t)
    buffer))

(ert-deftest herdr-follow-labels-renames-the-buffers-herdr-named ()
  (let* ((herdr-buffer-name-function
          (lambda (label _directory) (format "*herdr-follow: %s*" label)))
         (placeholder (herdr-tests--terminal-buffer
                       "*herdr-follow: agent*" "t1" "*herdr-follow: agent*"))
         (by-hand (herdr-tests--terminal-buffer
                   "*herdr-follow: mine*" "t2" "*herdr-follow: agent-2*")))
    (unwind-protect
        (progn
          (herdr-follow-labels
           '(((server_key . "/tmp/a.sock") (terminal_id . "t1")
              (terminal_title_stripped . "Tailscale to WireGuard replacement"))
             ((server_key . "/tmp/a.sock") (terminal_id . "t2")
              (terminal_title_stripped . "Another topic"))))
          (should (equal (buffer-name placeholder)
                         "*herdr-follow: Tailscale to WireGuard replacement*"))
          (should (equal (buffer-local-value 'herdr--buffer-name placeholder)
                         (buffer-name placeholder)))
          (should (equal (buffer-name by-hand) "*herdr-follow: mine*")))
      (let ((kill-buffer-query-functions nil))
        (mapc #'kill-buffer (list placeholder by-hand))))))

(ert-deftest herdr-attach-terminal-remembers-the-name-it-gave ()
  (let ((herdr-buffer-name-function
         (lambda (label _directory) (format "*herdr-given: %s*" label)))
        buffer)
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-session-server-key)
                   (lambda (_session) "/tmp/a.sock"))
                  ((symbol-function 'herdr--terminal-exec)
                   (lambda (target &rest _)
                     (make-process :name "herdr-given" :buffer target
                                   :command '("sleep" "30") :noquery t)
                     target)))
          (setq buffer (herdr-attach-terminal "t9" :session 'shared
                                              :label "Claude Code"))
          (should (equal (buffer-local-value 'herdr--buffer-name buffer)
                         "*herdr-given: Claude Code*")))
      (when (buffer-live-p buffer)
        (let ((kill-buffer-query-functions nil))
          (kill-buffer buffer))))))

(provide 'herdr-tests)
;;; herdr-tests.el ends here
