;;; herdr-transient-tests.el --- Herdr workflow UI tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'herdr-transient)

(ert-deftest herdr-transient-routes-workflows-without-spawning-processes ()
  (should (commandp 'herdr-transient))
  (let ((target '("server-a" . "term-7"))
        calls)
    (cl-letf (((symbol-function 'herdr-agent-start)
               (lambda (kind name &rest _) (push (list 'start kind name) calls)))
              ((symbol-function 'herdr-agent-continue)
               (lambda (kind name &rest _) (push (list 'continue kind name) calls)))
              ((symbol-function 'herdr-agent-resume)
               (lambda (kind name reference &rest _)
                 (push (list 'resume kind name reference) calls)))
              ((symbol-function 'herdr-agent-switch)
               (lambda (seen &rest _) (push (list 'switch seen) calls)))
              ((symbol-function 'herdr-agent-prompt)
               (lambda (seen text &rest _) (push (list 'prompt seen text) calls)))
              ((symbol-function 'herdr-agent-rename)
               (lambda (seen name &rest _) (push (list 'rename seen name) calls)))
              ((symbol-function 'herdr-agent-escape)
               (lambda (seen &rest _) (push (list 'escape seen) calls)))
              ((symbol-function 'herdr-agent-newline)
               (lambda (seen &rest _) (push (list 'newline seen) calls)))
              ((symbol-function 'herdr-agent-stop)
               (lambda (seen &rest _) (push (list 'stop seen) calls)))
              ((symbol-function 'herdr-agent-stop-all)
               (lambda (&rest _) (push '(stop-all) calls)))
              ((symbol-function 'start-process)
               (lambda (&rest _) (ert-fail "Transient action spawned a process")))
              ((symbol-function 'call-process)
               (lambda (&rest _) (ert-fail "Transient action spawned a process"))))
      (herdr-transient--start "claude" "review")
      (herdr-transient--continue "pi" "review")
      (herdr-transient--resume "codex" "review" "resume-7")
      (herdr-transient--switch target)
      (herdr-transient--prompt target "review this")
      (herdr-transient--rename target "audit")
      (herdr-transient--escape target)
      (herdr-transient--newline target)
      (herdr-transient--stop target)
      (herdr-transient--stop-all))
    (should
     (equal
      (nreverse calls)
      `((start "claude" "review")
        (continue "pi" "review")
        (resume "codex" "review" "resume-7")
        (switch ,target)
        (prompt ,target "review this")
        (rename ,target "audit")
        (escape ,target)
        (newline ,target)
        (stop ,target)
        (stop-all))))))

(ert-deftest herdr-transient-status-formatting-is-agent-specific ()
  (let ((view (herdr-transient--format-status
               '((agent . "claude")
                 (herdr_status . "connected")
                 (agent_status . "idle")))))
    (should (equal view "claude | Herdr: connected | Agent: idle"))))

(provide 'herdr-transient-tests)
;;; herdr-transient-tests.el ends here
