;;; herdr-agent-tests.el --- Tests for herdr-agent.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'json)
(require 'herdr)
(require 'herdr-api)
(require 'herdr-agent nil t)

(defconst herdr-agent-tests--harness-fixture
  (expand-file-name "testdata/herdr-agent-harnesses.json"
                    (file-name-directory (or load-file-name buffer-file-name))))

(defun herdr-agent-tests--harnesses ()
  (with-temp-buffer
    (insert-file-contents herdr-agent-tests--harness-fixture)
    (json-parse-buffer :object-type 'alist :array-type 'list)))

(defun herdr-agent-tests--harness-arguments (harness action reference)
  (mapcar (lambda (argument)
            (if (member argument '("ID" "PATH-OR-ID")) reference argument))
          (alist-get action harness)))

(defun herdr-agent-tests--require-functions (&rest functions)
  (dolist (function functions)
    (unless (fboundp function)
      (ert-fail (format "missing Herdr-native action: %s" function)))))

(defun herdr-agent-tests--pane (kind terminal-id pane-id workspace-id)
  `((agent . ,kind)
    (name . "review")
    (cwd . ,default-directory)
    (workspace_id . ,workspace-id)
    (tab_id . ,(concat workspace-id ":tab-1"))
    (pane_id . ,pane-id)
    (terminal_id . ,terminal-id)
    (agent_status . "idle")))

(defun herdr-agent-tests--agent (kind terminal-id pane-id workspace-id)
  `((terminal_id . ,terminal-id)
    (name . "review")
    (agent . ,kind)
    (agent_status . "idle")
    (agent_session . ((source . "herdr")
                      (agent . ,kind)
                      (kind . "session_id")
                      (value . "session-7")))
    (workspace_id . ,workspace-id)
    (tab_id . ,(concat workspace-id ":tab-1"))
    (pane_id . ,pane-id)
    (interactive_ready . t)
    (cwd . ,default-directory)))

(defun herdr-agent-tests--attachment (name terminal-id)
  (let ((buffer (generate-new-buffer (format " *herdr-agent-backend %s*" name))))
    (herdr-claim-buffer buffer terminal-id)
    (cons buffer (start-process (format "herdr-agent-%s" name) buffer "sleep" "30"))))

(defun herdr-agent-tests--dispose-attachment (attachment)
  (when-let* ((process (cdr attachment)) (process-live-p process))
    (delete-process process))
  (when-let* ((buffer (car attachment)) (buffer-live-p buffer))
    (kill-buffer buffer)))

(defun herdr-agent-tests--detach (session)
  (when (and session (fboundp 'herdr-agent-detach))
    (herdr-agent-detach session)))

(defun herdr-agent-tests--fail-cleanup ()
  (error "attachment cleanup failed"))

(defun herdr-agent-tests--unexpected-cli (&rest _)
  (error "Herdr-native actions must not spawn a CLI"))

(ert-deftest herdr-agent-shared-server-key-survives-a-missing-symlinked-parent ()
  (let* ((root (make-temp-file "herdr-agent-key" t))
         (real-root (expand-file-name "real" root))
         (alias-root (expand-file-name "alias" root))
         (real-parent (expand-file-name "socket-parent" real-root))
         (alias-socket (expand-file-name "herdr.sock"
                                         (expand-file-name "socket-parent" alias-root)))
         (real-socket (expand-file-name "herdr.sock" real-parent)))
    (unwind-protect
        (progn
          (make-directory real-root t)
          (make-symbolic-link real-root alias-root)
          (let ((herdr-socket-path alias-socket))
            (let ((before (herdr-server-key)))
              (make-directory real-parent t)
              (let ((expected (file-truename real-socket)))
                (should (equal before expected))
                (should (equal (herdr-server-key) expected))
                (let ((herdr-socket-path real-socket))
                  (should (equal (herdr-server-key) expected)))))))
      (delete-directory root t))))

(ert-deftest herdr-agent-adoption-separates-same-label-terminal-on-explicit-servers ()
  (let* ((root (make-temp-file "herdr-agent-servers" t))
         (socket-a (expand-file-name "a/herdr.sock" root))
         (socket-b (expand-file-name "b/herdr.sock" root))
         server-a server-b
         (attachments nil)
         (routed nil)
         first-buffer second-buffer first second)
    (unwind-protect
        (progn
          (make-directory (file-name-directory socket-a) t)
          (make-directory (file-name-directory socket-b) t)
          (let ((herdr-socket-path socket-a))
            (setq server-a (herdr-server-key)))
          (let ((herdr-socket-path socket-b))
            (setq server-b (herdr-server-key)))
          (let ((herdr-attach-functions (list #'herdr-agent-attach-entry)))
            (cl-letf (((symbol-function 'herdr--terminal-exec)
                       (lambda (buffer &rest _)
                         (push herdr-socket-path routed)
                         (let ((process
                                (start-process (format "herdr-agent-%s" (buffer-name buffer))
                                               buffer "sleep" "30")))
                           (push (cons buffer process) attachments)
                           buffer))))
              (let ((herdr-socket-path socket-a))
                (setq first-buffer
                      (herdr-attach-entry
                       (herdr-agent-tests--agent "claude" "term-shared" "a:pane" "a"))))
              (let ((herdr-socket-path socket-b))
                (setq second-buffer
                      (herdr-attach-entry
                       (herdr-agent-tests--agent "claude" "term-shared" "b:pane" "b"))))
              (setq first (herdr-agent-find server-a "term-shared")
                    second (herdr-agent-find server-b "term-shared"))
              (should (buffer-live-p first-buffer))
              (should (buffer-live-p second-buffer))
              (should-not (eq first-buffer second-buffer))
              (should (equal (buffer-name first-buffer) "*herdr: review*"))
              (should (equal (buffer-name second-buffer) "*herdr: review<2>*"))
              (should (eq (herdr-agent-session-buffer first) first-buffer))
              (should (eq (herdr-agent-session-buffer second) second-buffer))
              (should (equal (buffer-local-value 'herdr-terminal-server-key first-buffer)
                             server-a))
              (should (equal (buffer-local-value 'herdr-terminal-server-key second-buffer)
                             server-b))
              (should (equal (nreverse routed) (list server-a server-b)))))
      (herdr-agent-tests--detach first)
      (herdr-agent-tests--detach second)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t)))))

(ert-deftest herdr-agent-start-in-pane-uses-returned-agent-identity-for-three-kinds ()
  (let* ((root (make-temp-file "herdr-agent-start" t))
         (server-key (expand-file-name "herdr.sock" root))
         (fixtures '(("claude" "pending-claude" "agent-claude")
                     ("pi" "pending-pi" "agent-pi")
                     ("codex" "pending-codex" "agent-codex")))
         (attachments nil)
         (starts nil)
         (adapted nil)
         sessions)
    (unwind-protect
        (let ((herdr-agent-kind-adapters
               `(("claude" . ,(lambda (session)
                                  (push "claude" adapted)
                                  (with-current-buffer (herdr-agent-session-buffer session)
                                    (setq-local herdr-agent-tests--ide-state "claude")))))))
          (cl-letf (((symbol-function 'herdr-api-agent-start)
                     (lambda (kind name pane-id &rest arguments)
                       (push (list kind name pane-id arguments) starts)
                       (let ((fixture (assoc kind fixtures)))
                         `((agent . ,(herdr-agent-tests--agent
                                      kind (nth 2 fixture) pane-id "work"))
                           (argv . ("herdr" "agent" ,kind))))))
                    ((symbol-function 'herdr-attach-terminal)
                     (lambda (terminal-id &rest _)
                       (let ((attachment
                              (herdr-agent-tests--attachment terminal-id terminal-id)))
                         (push attachment attachments)
                         (car attachment)))))
            (dolist (fixture fixtures)
              (pcase-let ((`(,kind ,provisional ,final) fixture))
                (let ((session
                       (herdr-agent-start-in-pane
                        kind "review"
                        (herdr-agent-tests--pane kind provisional
                                                 (concat kind ":pane") "work")
                        :server-key server-key :args '())))
                  (push session sessions)
                  (should (process-live-p
                           (herdr-agent-session-attachment-process session)))
                  (should (equal (herdr-agent-session-key session)
                                 (cons server-key final)))
                  (should (eq (herdr-agent-find server-key final) session))
                  (should-not (herdr-agent-find server-key provisional))
                  (if (equal kind "claude")
                      (should (equal (buffer-local-value 'herdr-agent-tests--ide-state
                                                         (herdr-agent-session-buffer session))
                                     "claude"))
                    (should-not (local-variable-p 'herdr-agent-tests--ide-state
                                                  (herdr-agent-session-buffer session)))))))
            (should (equal (mapcar (lambda (call) (cl-subseq call 0 4))
                                   (nreverse starts))
                           '(("claude" "review" "claude:pane" (:args nil))
                             ("pi" "review" "pi:pane" (:args nil))
                             ("codex" "review" "codex:pane" (:args nil)))))
            (should (equal adapted '("claude")))))
      (mapc #'herdr-agent-tests--detach sessions)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t))))

(ert-deftest herdr-agent-adoption-reuses-three-kinds-and-cleans-a-failed-attachment ()
  (let* ((root (make-temp-file "herdr-agent-adoption" t))
         (server-key (expand-file-name "herdr.sock" root))
         (fixtures '(("claude" . "term-claude")
                     ("pi" . "term-pi")
                     ("codex" . "term-codex")))
         (attachments nil)
         (attachment-count 0)
         claude-agent claude-session sessions)
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-api-agent-start)
                   (lambda (&rest _) (error "adoption must not launch an agent")))
                  ((symbol-function 'herdr-attach-terminal)
                   (lambda (terminal-id &rest _)
                     (cl-incf attachment-count)
                     (if (equal terminal-id "term-failed")
                         (error "attachment creation failed")
                       (let ((attachment
                              (herdr-agent-tests--attachment terminal-id terminal-id)))
                         (push attachment attachments)
                         (car attachment))))))
          (dolist (fixture fixtures)
            (pcase-let ((`(,kind . ,terminal-id) fixture))
              (let* ((agent (herdr-agent-tests--agent kind terminal-id
                                                       (concat terminal-id ":pane") "work"))
                     (first (herdr-agent-adopt agent :server-key server-key))
                     (second (herdr-agent-adopt agent :server-key server-key)))
                (push first sessions)
                (when (equal kind "claude")
                  (setq claude-agent agent
                        claude-session first))
                (should (eq first second))
                (should (eq (herdr-agent-find server-key terminal-id) first)))))
          (let ((error
                 (should-error
                  (herdr-agent-adopt
                   (herdr-agent-tests--agent "pi" "term-failed" "failed:pane" "work")
                   :server-key server-key))))
            (should (equal (error-message-string error) "attachment creation failed")))
          (should (= attachment-count 4))
          (should-not (herdr-agent-find server-key "term-failed")))
      (mapc #'herdr-agent-tests--detach sessions)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t))))

(ert-deftest herdr-agent-event-subscriptions-route-data-per-server-and-repair-moves ()
  (let* ((root (make-temp-file "herdr-agent-events" t))
         (socket-a (expand-file-name "a/herdr.sock" root))
         (socket-b (expand-file-name "b/herdr.sock" root))
         server-a server-b
         (attachments nil)
         (callbacks (make-hash-table :test #'equal))
         (subscriptions nil)
         session-a session-b)
    (unwind-protect
        (progn
          (make-directory (file-name-directory socket-a) t)
          (make-directory (file-name-directory socket-b) t)
          (let ((herdr-socket-path socket-a))
            (setq server-a (herdr-server-key)))
          (let ((herdr-socket-path socket-b))
            (setq server-b (herdr-server-key)))
          (cl-letf (((symbol-function 'herdr-attach-terminal)
                     (lambda (terminal-id &rest _)
                       (let ((attachment
                              (herdr-agent-tests--attachment terminal-id terminal-id)))
                         (push attachment attachments)
                         (car attachment))))
                    ((symbol-function 'herdr-subscribe)
                     (lambda (types callback &rest _)
                       (should (listp types))
                       (push (cons (herdr-server-key) types) subscriptions)
                       (dolist (type types)
                         (puthash (cons (herdr-server-key) type) callback callbacks)))))
            (setq session-a
                  (herdr-agent-adopt
                   (herdr-agent-tests--agent "claude" "term-shared" "a:old" "a")
                   :server-key server-a)
                  session-b
                  (herdr-agent-adopt
                   (herdr-agent-tests--agent "pi" "term-shared" "b:only" "b")
                   :server-key server-b))
            (let ((herdr-socket-path socket-a)) (herdr-agent-subscribe server-a))
            (let ((herdr-socket-path socket-b)) (herdr-agent-subscribe server-b))
            (dolist (server-key (list server-a server-b))
              (should (equal
                       (sort
                        (mapcar #'cdr
                                (cl-remove-if-not
                                 (lambda (subscription)
                                   (equal (car subscription) server-key))
                                 subscriptions))
                        (lambda (left right)
                          (string-lessp (car left) (car right))))
                       '(("pane.agent_detected") ("pane.closed") ("pane.exited")
                         ("pane.moved") ("pane.updated")))))
            (funcall (gethash (cons server-a "pane.updated") callbacks)
                     `((pane . ,(herdr-agent-tests--pane "claude" "term-shared" "a:old" "a"))))
            (funcall (gethash (cons server-a "pane.moved") callbacks)
                     `((previous_pane_id . "a:old")
                       (previous_workspace_id . "a")
                       (previous_tab_id . "a:tab-1")
                       (pane . ,(herdr-agent-tests--pane "claude" "term-shared" "a:new" "a"))))
            (funcall (gethash (cons server-a "pane.agent_detected") callbacks)
                     '((pane_id . "a:old") (workspace_id . "a") (released . t)))
            (should (eq (herdr-agent-find server-a "term-shared") session-a))
            (funcall (gethash (cons server-a "pane.exited") callbacks)
                     '((pane_id . "a:new") (workspace_id . "a")))
            (should-not (herdr-agent-find server-a "term-shared"))
            (funcall (gethash (cons server-a "pane.closed") callbacks)
                     '((pane_id . "a:gone") (workspace_id . "a")))
            (should (eq (herdr-agent-find server-b "term-shared") session-b))))
      (herdr-agent-tests--detach session-a)
      (herdr-agent-tests--detach session-b)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t))))

(ert-deftest herdr-agent-detach-and-attachment-death-keep-herdr-open-and-retry-cleanup ()
  (let* ((root (make-temp-file "herdr-agent-detach" t))
         (server-key (expand-file-name "herdr.sock" root))
         (attachments nil)
         (requests nil)
         dead-session retry-session)
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-attach-terminal)
                   (lambda (terminal-id &rest _)
                     (let ((attachment
                            (herdr-agent-tests--attachment terminal-id terminal-id)))
                       (push attachment attachments)
                       (car attachment))))
                  ((symbol-function 'herdr-request)
                   (lambda (method &rest _)
                     (push method requests)
                     '((type . "ok")))))
          (setq dead-session
                (herdr-agent-adopt
                 (herdr-agent-tests--agent "codex" "term-death" "death:pane" "work")
                 :server-key server-key))
          (delete-process (herdr-agent-session-attachment-process dead-session))
          (accept-process-output nil 0.05)
          (should (eq (herdr-agent-session-state dead-session) 'stopped))
          (should-not (herdr-agent-find server-key "term-death"))
          (should-not requests)
          (setq retry-session
                (herdr-agent-adopt
                 (herdr-agent-tests--agent "pi" "term-retry" "retry:pane" "work")
                 :server-key server-key))
          (with-current-buffer (herdr-agent-session-buffer retry-session)
            (add-hook 'kill-buffer-hook #'herdr-agent-tests--fail-cleanup nil t))
          (herdr-agent-detach retry-session)
          (should (eq (herdr-agent-session-state retry-session) 'detaching))
          (should (eq (herdr-agent-find server-key "term-retry") retry-session))
          (should-not requests)
          (with-current-buffer (herdr-agent-session-buffer retry-session)
            (remove-hook 'kill-buffer-hook #'herdr-agent-tests--fail-cleanup t))
          (herdr-agent-detach retry-session)
          (should (eq (herdr-agent-session-state retry-session) 'stopped))
          (should-not (herdr-agent-find server-key "term-retry"))
          (should-not requests))
      (herdr-agent-tests--detach dead-session)
      (herdr-agent-tests--detach retry-session)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t))))

(ert-deftest herdr-agent-start-rollback-cleans-only-transaction-owned-resources ()
  (let ((root (make-temp-file "herdr-agent-rollback" t)))
    (unwind-protect
        (dolist (case '(("borrowed" nil 1 1 (agent-start tab-close))
                        ("owned-empty" t 0 0 (agent-start tab-close workspace-list workspace-close))
                        ("owned-nonempty" t 1 1 (agent-start tab-close workspace-list))))
          (pcase-let ((`(,workspace-id ,owned ,tab-count ,pane-count ,expected-operations) case))
            (let ((operations nil)
                  (server-key (expand-file-name (concat workspace-id "/herdr.sock") root)))
              (cl-letf (((symbol-function 'herdr-start-server-if-needed)
                         (lambda (&rest _) t))
                        ((symbol-function 'herdr-workspace-id)
                         (lambda (&rest _) (and (not owned) workspace-id)))
                        ((symbol-function 'herdr-open-tab)
                         (lambda (&rest _)
                           `((workspace . ((workspace_id . ,workspace-id)
                                            (label . "review")))
                             (tab . ((tab_id . ,(concat workspace-id ":owned"))
                                     (workspace_id . ,workspace-id)))
                             (root_pane . ((pane_id . ,(concat workspace-id ":owned:root"))
                                           (tab_id . ,(concat workspace-id ":owned"))
                                           (workspace_id . ,workspace-id))))))
                        ((symbol-function 'herdr-api-agent-start)
                         (lambda (&rest _)
                           (push 'agent-start operations)
                           (signal 'herdr-error (list "agent start failed"))))
                        ((symbol-function 'herdr-api-tab-close)
                         (lambda (&rest _)
                           (push 'tab-close operations)))
                        ((symbol-function 'herdr-api-workspace-list)
                         (lambda ()
                           (push 'workspace-list operations)
                           `((workspaces . (((workspace_id . ,workspace-id)
                                             (tab_count . ,tab-count)
                                             (pane_count . ,pane-count)))))))
                        ((symbol-function 'herdr-api-workspace-close)
                         (lambda (&rest _) (push 'workspace-close operations))))
                (let ((error
                       (should-error
                        (herdr-agent-start-session "claude" "review"
                                                   :server-key server-key
                                                   :project-root root))))
                  (should (equal (cadr error) "agent start failed")))
                (should (equal (nreverse operations) expected-operations))))))
      (delete-directory root t))))

(ert-deftest herdr-agent-native-harness-fixture-is-exact ()
  (should
   (equal
    (herdr-agent-tests--harnesses)
    '(((kind . "claude") (name . "Claude Code") (version . "2.1.235")
       (start) (continue "--continue") (resume "--resume" "ID"))
      ((kind . "pi") (name . "Pi") (version . "0.82.1")
       (start) (continue "--continue") (resume "--session" "PATH-OR-ID"))
      ((kind . "codex") (name . "Codex") (version . "0.148.0")
       (start) (continue "resume" "--last") (resume "resume" "ID"))))))

(ert-deftest herdr-agent-native-start-continue-and-resume-use-harness-arguments ()
  (herdr-agent-tests--require-functions
   'herdr-agent-start 'herdr-agent-continue 'herdr-agent-resume)
  (let* ((root (make-temp-file "herdr-agent-native-launch" t))
         (server-key (expand-file-name "herdr.sock" root))
         (attachments nil)
         (starts nil)
         sessions)
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-start-server-if-needed)
                   (lambda (&rest _) t))
                  ((symbol-function 'herdr-workspace-id)
                   (lambda (&rest _) "work"))
                  ((symbol-function 'herdr-api-tab-create)
                   (lambda (&rest _)
                     '((tab . ((tab_id . "work:tab") (workspace_id . "work")))
                       (root_pane . ((pane_id . "work:tab:root")
                                     (tab_id . "work:tab")
                                     (workspace_id . "work"))))))
                  ((symbol-function 'herdr-api-agent-start)
                   (lambda (kind name pane-id &rest arguments)
                     (push (list kind name pane-id arguments) starts)
                     `((agent . ,(herdr-agent-tests--agent
                                  kind (concat pane-id ":terminal") pane-id "work")))))
                  ((symbol-function 'herdr-attach-terminal)
                   (lambda (terminal-id &rest _)
                     (let ((attachment
                            (herdr-agent-tests--attachment terminal-id terminal-id)))
                       (push attachment attachments)
                       (car attachment)))))
          (dolist (harness (herdr-agent-tests--harnesses))
            (let* ((kind (alist-get 'kind harness))
                   (reference (format "%s-session" kind)))
              (push (herdr-agent-start kind "review"
                                       :server-key server-key :project-root root)
                    sessions)
              (push (herdr-agent-continue kind "review"
                                          :server-key server-key :project-root root)
                    sessions)
              (push (herdr-agent-resume kind "review" reference
                                        :server-key server-key :project-root root)
                    sessions)
              (setq starts (nreverse starts))
              (should (equal (mapcar (lambda (call)
                                       (list (car call) (nth 3 call)))
                                     starts)
                             (mapcar
                              (lambda (action)
                                (list kind
                                      (list :args
                                            (herdr-agent-tests--harness-arguments
                                             harness action reference))))
                              '(start continue resume))))
              (setq starts nil)
              (should-error
               (herdr-agent-resume kind "review" nil
                                   :server-key server-key :project-root root)
               :type 'user-error)
              (should-not starts)))
      (mapc #'herdr-agent-tests--detach sessions)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t)))))

(ert-deftest herdr-agent-native-target-resolution-is-explicit-project-local-and-mru ()
  (herdr-agent-tests--require-functions 'herdr-agent-resolve-target)
  (let* ((project "/projects/alpha/")
         (agents '(((terminal_id . "foreign") (agent . "aider")
                   (cwd . "/projects/beta/"))
                  ((terminal_id . "alpha-old") (agent . "pi")
                   (cwd . "/projects/alpha/"))
                  ((terminal_id . "alpha-recent") (agent . "claude")
                   (cwd . "/projects/alpha/lib/"))))
         (mru '("foreign" "alpha-recent"))
         (picker-used nil))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _) (setq picker-used t) "foreign")))
      (should (equal (alist-get 'terminal_id
                                (herdr-agent-resolve-target "foreign" agents project mru))
                     "foreign"))
      (should (equal (alist-get 'terminal_id
                                (herdr-agent-resolve-target nil agents project mru))
                     "alpha-recent"))
      (should-error (herdr-agent-resolve-target "missing" agents project mru)
                    :type 'user-error)
      (should-error (herdr-agent-resolve-target nil agents project nil)
                    :type 'user-error)
      (should-not picker-used))))

(ert-deftest herdr-agent-native-management-uses-herdr-api-wrappers ()
  (herdr-agent-tests--require-functions
   'herdr-agent-list 'herdr-agent-switch 'herdr-agent-rename
   'herdr-agent-status 'herdr-agent-stop 'herdr-agent-stop-all)
  (let* ((agents '(((terminal_id . "term-a") (pane_id . "w:p-a")
                    (agent . "claude") (name . "review"))
                   ((terminal_id . "term-b") (pane_id . "w:p-b")
                    (agent . "aider") (name . "generic"))))
         (calls nil))
    (cl-letf (((symbol-function 'herdr-api-agent-list)
               (lambda () (push '(list) calls) `((agents . ,agents))))
              ((symbol-function 'herdr-api-agent-focus)
               (lambda (target) (push (list 'focus target) calls)))
              ((symbol-function 'herdr-api-agent-rename)
               (lambda (target &rest arguments)
                 (push (list 'rename target arguments) calls)))
              ((symbol-function 'herdr-api-agent-get)
               (lambda (target)
                 (push (list 'get target) calls)
                 (if-let ((agent (cl-find target agents :key (lambda (agent)
                                                              (alist-get 'terminal_id agent))
                                         :test #'equal)))
                     `((agent . ,agent))
                   (signal 'user-error (list "unknown agent")))))
              ((symbol-function 'herdr-api-pane-close)
               (lambda (pane-id) (push (list 'close pane-id) calls)))
              ((symbol-function 'herdr--terminal-exec)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'start-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'process-file)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'shell-command)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process-shell-command)
               #'herdr-agent-tests--unexpected-cli))
      (should (equal (herdr-agent-list) agents))
      (herdr-agent-rename "term-a" "renamed")
      (herdr-agent-status "term-a")
      (herdr-agent-stop "term-a")
      (setq calls (nreverse calls))
      (should (member '(rename "term-a" (:name "renamed")) calls))
      (should (member '(get "term-a") calls))
      (should (member '(close "w:p-a") calls))
      (should-not (member '(close "w:p-b") calls))
      (setq calls nil)
      (herdr-agent-stop-all)
      (setq calls (nreverse calls))
      (should (member '(close "w:p-a") calls))
      (should (member '(close "w:p-b") calls)))))

(ert-deftest herdr-agent-native-prompt-escape-and-newline-use-agent-api ()
  (herdr-agent-tests--require-functions
   'herdr-agent-prompt 'herdr-agent-escape 'herdr-agent-newline)
  (let ((calls nil))
    (cl-letf (((symbol-function 'herdr-api-agent-prompt)
               (lambda (target text &rest arguments)
                 (push (list 'prompt target text arguments) calls)))
              ((symbol-function 'herdr-api-agent-send-keys)
               (lambda (keys target) (push (list 'keys keys target) calls)))
              ((symbol-function 'herdr-api-pane-send-text)
               (lambda (&rest _) (error "interaction must use the agent API")))
              ((symbol-function 'herdr--terminal-exec)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'start-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'process-file)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'shell-command)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process-shell-command)
               #'herdr-agent-tests--unexpected-cli))
      (herdr-agent-prompt "term-a" "Write the tests")
      (herdr-agent-escape "term-a")
      (herdr-agent-newline "term-a")
      (should
       (equal (nreverse calls)
              '((prompt "term-a" "Write the tests" nil)
                (keys ("esc") "term-a")
                (keys ("enter") "term-a")))))))

(ert-deftest herdr-agent-native-switch-focuses-the-visible-owned-terminal ()
  (herdr-agent-tests--require-functions 'herdr-agent-switch)
  (let ((buffer (get-buffer-create " *herdr-agent-native-visible*"))
        (focused nil)
        (attached nil)
        (created-tab nil)
        (herdr-use-side-window t)
        (herdr-window-side 'right)
        (herdr-window-width 20)
        (herdr-display-buffer-action nil))
    (unwind-protect
        (cl-letf (((symbol-function 'herdr-api-agent-focus)
                   (lambda (target) (setq focused target)))
                  ((symbol-function 'herdr-terminal-buffer)
                   (lambda (terminal-id &optional _server-key)
                     (and (equal terminal-id "term-a") buffer)))
                  ((symbol-function 'herdr-attach-terminal)
                   (lambda (&rest _) (setq attached t)))
                  ((symbol-function 'herdr-api-tab-create)
                   (lambda (&rest _) (setq created-tab t))))
          (let ((window (herdr-agent-switch "term-a")))
            (should (equal focused "term-a"))
            (should (windowp window))
            (should (eq (window-buffer window) buffer))
            (should (eq (selected-window) window))
            (should (eq (window-parameter window 'window-side) 'right))
            (should (window-live-p (get-buffer-window buffer t)))
            (should-not attached)
            (should-not created-tab)))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))))

(ert-deftest herdr-agent-native-composite-target-routes-every-action-to-owning-server ()
  (herdr-agent-tests--require-functions
   'herdr-agent-list 'herdr-agent-switch 'herdr-agent-rename
   'herdr-agent-status 'herdr-agent-stop 'herdr-agent-stop-all
   'herdr-agent-prompt 'herdr-agent-escape 'herdr-agent-newline)
  (let* ((root (make-temp-file "herdr-agent-composite" t))
         (socket-a (expand-file-name "a/herdr.sock" root))
         (socket-b (expand-file-name "b/herdr.sock" root))
         (attachments nil)
         (calls nil)
         session-a session-b server-a server-b)
    (unwind-protect
        (progn
          (make-directory (file-name-directory socket-a) t)
          (make-directory (file-name-directory socket-b) t)
          (let ((herdr-socket-path socket-a))
            (setq server-a (herdr-server-key)))
          (let ((herdr-socket-path socket-b))
            (setq server-b (herdr-server-key)))
          (cl-letf (((symbol-function 'herdr-attach-terminal)
                     (lambda (terminal-id &rest _)
                       (let ((attachment
                              (herdr-agent-tests--attachment terminal-id terminal-id)))
                         (push attachment attachments)
                         (car attachment)))))
            (setq session-a
                  (herdr-agent-adopt
                   (herdr-agent-tests--agent "claude" "shared" "a:pane" "a")
                   :server-key server-a)
                  session-b
                  (herdr-agent-adopt
                   (herdr-agent-tests--agent "pi" "shared" "b:pane" "b")
                   :server-key server-b)))
          (let ((target (cons server-a "shared"))
                (agent-a (herdr-agent-tests--agent "claude" "shared" "a:pane" "a"))
                (herdr-socket-path server-b))
            (cl-letf (((symbol-function 'herdr-api-agent-list)
                       (lambda ()
                         (push (list herdr-socket-path 'list) calls)
                         `((agents . (,agent-a)))))
                      ((symbol-function 'herdr-api-agent-focus)
                       (lambda (terminal-id)
                         (push (list herdr-socket-path 'focus terminal-id) calls)))
                      ((symbol-function 'herdr-api-agent-rename)
                       (lambda (terminal-id &rest arguments)
                         (push (list herdr-socket-path 'rename terminal-id arguments) calls)))
                      ((symbol-function 'herdr-api-agent-get)
                       (lambda (terminal-id)
                         (push (list herdr-socket-path 'get terminal-id) calls)
                         `((agent . ,agent-a))))
                      ((symbol-function 'herdr-api-pane-close)
                       (lambda (pane-id)
                         (push (list herdr-socket-path 'close pane-id) calls)))
                      ((symbol-function 'herdr-api-agent-prompt)
                       (lambda (terminal-id text &rest arguments)
                         (push (list herdr-socket-path 'prompt terminal-id text arguments) calls)))
                      ((symbol-function 'herdr-api-agent-send-keys)
                       (lambda (keys terminal-id)
                         (push (list herdr-socket-path 'keys keys terminal-id) calls)))
                      ((symbol-function 'herdr-terminal-buffer)
                       (lambda (terminal-id &optional server-key)
                         (push (list herdr-socket-path 'buffer terminal-id server-key) calls)
                         (herdr-agent-session-buffer session-a)))
                      ((symbol-function 'herdr--terminal-exec)
                       #'herdr-agent-tests--unexpected-cli)
                      ((symbol-function 'start-process)
                       #'herdr-agent-tests--unexpected-cli)
                      ((symbol-function 'process-file)
                       #'herdr-agent-tests--unexpected-cli)
                      ((symbol-function 'call-process)
                       #'herdr-agent-tests--unexpected-cli)
                      ((symbol-function 'shell-command)
                       #'herdr-agent-tests--unexpected-cli)
                      ((symbol-function 'call-process-shell-command)
                       #'herdr-agent-tests--unexpected-cli))
              (let ((herdr-socket-path server-a))
                (should (equal (herdr-agent-list) (list agent-a))))
              (herdr-agent-switch target)
              (herdr-agent-rename target "renamed")
              (let ((status (herdr-agent-status target)))
                (herdr-agent-stop target)
                (herdr-agent-prompt target "Write the tests")
                (herdr-agent-escape target)
                (herdr-agent-newline target)
                (let ((herdr-socket-path server-a))
                  (herdr-agent-stop-all))
                (should (equal status agent-a)))
              (should
               (equal
                (nreverse calls)
                `((,server-a list)
                  (,server-a focus "shared")
                  (,server-a buffer "shared" ,server-a)
                  (,server-a rename "shared" (:name "renamed"))
                  (,server-a get "shared")
                  (,server-a get "shared")
                  (,server-a close "a:pane")
                  (,server-a prompt "shared" "Write the tests" nil)
                  (,server-a keys ("esc") "shared")
                  (,server-a keys ("enter") "shared")
                  (,server-a list)
                  (,server-a close "a:pane")))))))
      (herdr-agent-tests--detach session-a)
      (herdr-agent-tests--detach session-b)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t))))

(ert-deftest herdr-agent-native-public-target-ladder-keeps-composite-identity ()
  (herdr-agent-tests--require-functions
   'herdr-agent-adopt 'herdr-agent-prompt)
  (let* ((root (make-temp-file "herdr-agent-target-ladder" t))
         (project-a (expand-file-name "project-a" root))
         (project-b (expand-file-name "project-b" root))
         (socket-a (expand-file-name "a/herdr.sock" root))
         (socket-b (expand-file-name "b/herdr.sock" root))
         (socket-c (expand-file-name "c/herdr.sock" root))
         (attachments nil)
         (calls nil)
         session-a session-b server-a server-b server-c)
    (unwind-protect
        (progn
          (make-directory project-a t)
          (make-directory project-b t)
          (make-directory (file-name-directory socket-a) t)
          (make-directory (file-name-directory socket-b) t)
          (make-directory (file-name-directory socket-c) t)
          (let ((herdr-socket-path socket-a))
            (setq server-a (herdr-server-key)))
          (let ((herdr-socket-path socket-b))
            (setq server-b (herdr-server-key)))
          (let ((herdr-socket-path socket-c))
            (setq server-c (herdr-server-key)))
          (cl-letf (((symbol-function 'herdr-attach-terminal)
                     (lambda (terminal-id &rest _)
                       (let ((attachment
                              (herdr-agent-tests--attachment terminal-id terminal-id)))
                         (push attachment attachments)
                         (car attachment)))))
            (let ((default-directory project-a))
              (setq session-a
                    (herdr-agent-adopt
                     (herdr-agent-tests--agent "claude" "foreign" "a:pane" "a")
                     :server-key server-a)))
            (let ((default-directory project-b))
              (setq session-b
                    (herdr-agent-adopt
                     (herdr-agent-tests--agent "pi" "local" "b:pane" "b")
                     :server-key server-b))))
          (let ((herdr-socket-path server-c))
            (cl-letf (((symbol-function 'herdr-api-agent-prompt)
                       (lambda (terminal-id text &rest _)
                         (push (list herdr-socket-path terminal-id text) calls))))
              (with-current-buffer (herdr-agent-session-buffer session-a)
                (herdr-agent-prompt nil "attached"))
              (herdr-agent-prompt (cons server-b "local") "explicit")
              (let ((visible-source (generate-new-buffer " *herdr-agent-target-source*")))
                (unwind-protect
                    (save-window-excursion
                      (switch-to-buffer visible-source)
                      (with-current-buffer visible-source
                        (setq default-directory project-b))
                      (set-window-buffer (split-window-right)
                                         (herdr-agent-session-buffer session-a))
                      (herdr-agent-prompt nil "visible"))
                  (when (buffer-live-p visible-source)
                    (kill-buffer visible-source))))
              (with-temp-buffer
                (setq default-directory project-b)
                (herdr-agent-prompt nil "project-mru"))
              (should
               (equal (nreverse calls)
                      `((,server-a "foreign" "attached")
                        (,server-b "local" "explicit")
                        (,server-b "local" "visible")
                        (,server-b "local" "project-mru"))))))
      (herdr-agent-tests--detach session-a)
      (herdr-agent-tests--detach session-b)
      (mapc #'herdr-agent-tests--dispose-attachment attachments)
      (delete-directory root t)))))

(ert-deftest herdr-agent-native-resume-rejects-empty-reference-and-generic-kind ()
  (herdr-agent-tests--require-functions 'herdr-agent-start 'herdr-agent-resume)
  (let ((starts nil)
        (server-starts nil)
        (conditions nil))
    (cl-letf (((symbol-function 'herdr-start-server-if-needed)
               (lambda (&rest _)
                 (push t server-starts)))
              ((symbol-function 'herdr-api-agent-start)
               (lambda (&rest arguments)
                 (push arguments starts)
                 (error "agent.start must not be called")))
              ((symbol-function 'herdr--terminal-exec)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'start-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'process-file)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'shell-command)
               #'herdr-agent-tests--unexpected-cli)
              ((symbol-function 'call-process-shell-command)
               #'herdr-agent-tests--unexpected-cli))
      (dolist (kind '("claude" "pi" "codex"))
        (dolist (reference '(nil ""))
          (push (condition-case error
                    (progn
                      (herdr-agent-resume kind "review" reference)
                      '(returned))
                  (error error))
                conditions)))
      (push (condition-case error
                (progn
                  (herdr-agent-start "aider" "review")
                  '(returned))
              (error error))
            conditions)
      (should (equal (mapcar #'car (nreverse conditions))
                     '(user-error user-error user-error user-error
                       user-error user-error herdr-error)))
      (should-not starts)
      (should-not server-starts))))

(provide 'herdr-agent-tests)
;;; herdr-agent-tests.el ends here
