;;; herdr-api.el --- Wrappers for the herdr socket API -*- lexical-binding: t; -*-

;;; Commentary:

;; Generated by tools/herdr-api-gen.el from herdr protocol 17.
;; Every method of the herdr socket API gets one function; see
;; https://herdr.dev/docs/socket-api/ for what each of them does.
;; Do not edit by hand: regenerate after a herdr upgrade.

;;; Code:

(require 'cl-lib)
(require 'herdr-core)

(defconst herdr-api-protocol 17
  "Herdr socket protocol version these wrappers were generated from.")

(defun herdr-api-ping ()
  "Call the herdr API method `ping'.

Return the result alist."
  (herdr-request "ping"))

(defun herdr-api-server-stop ()
  "Call the herdr API method `server.stop'.

Return the result alist."
  (herdr-request "server.stop"))

(cl-defun herdr-api-server-live-handoff
    (&key expected-protocol expected-version import-exe)
  "Call the herdr API method `server.live_handoff'.

Keyword arguments: EXPECTED-PROTOCOL, EXPECTED-VERSION, IMPORT-EXE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "server.live_handoff"
                 (herdr--params
                  (list (cons 'expected_protocol expected-protocol)
                        (cons 'expected_version expected-version)
                        (cons 'import_exe import-exe)))))

(defun herdr-api-server-reload-config ()
  "Call the herdr API method `server.reload_config'.

Return the result alist."
  (herdr-request "server.reload_config"))

(defun herdr-api-server-agent-manifests ()
  "Call the herdr API method `server.agent_manifests'.

Return the result alist."
  (herdr-request "server.agent_manifests"))

(defun herdr-api-server-reload-agent-manifests ()
  "Call the herdr API method `server.reload_agent_manifests'.

Return the result alist."
  (herdr-request "server.reload_agent_manifests"))

(cl-defun herdr-api-notification-show (title &key body position sound)
  "Call the herdr API method `notification.show'.

TITLE is required.

Keyword arguments: BODY, POSITION, SOUND.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "notification.show"
                 (herdr--params
                  (list (cons 'title title) (cons 'body body)
                        (cons 'position position) (cons 'sound sound)))))

(defun herdr-api-client-window-title-set (title)
  "Call the herdr API method `client.window_title.set'.

TITLE is required.

Return the result alist."
  (herdr-request "client.window_title.set"
                 (herdr--params (list (cons 'title title)))))

(defun herdr-api-client-window-title-clear ()
  "Call the herdr API method `client.window_title.clear'.

Return the result alist."
  (herdr-request "client.window_title.clear"))

(defun herdr-api-session-snapshot ()
  "Call the herdr API method `session.snapshot'.

Return the result alist."
  (herdr-request "session.snapshot"))

(cl-defun herdr-api-workspace-create (&key cwd env focus label)
  "Call the herdr API method `workspace.create'.

Keyword arguments: CWD, ENV, FOCUS, LABEL.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "workspace.create"
                 (herdr--params
                  (list (cons 'cwd cwd) (cons 'env env)
                        (cons 'focus focus) (cons 'label label)))))

(defun herdr-api-workspace-list ()
  "Call the herdr API method `workspace.list'.

Return the result alist."
  (herdr-request "workspace.list"))

(defun herdr-api-workspace-get (workspace-id)
  "Call the herdr API method `workspace.get'.

WORKSPACE-ID is required.

Return the result alist."
  (herdr-request "workspace.get"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)))))

(defun herdr-api-workspace-focus (workspace-id)
  "Call the herdr API method `workspace.focus'.

WORKSPACE-ID is required.

Return the result alist."
  (herdr-request "workspace.focus"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)))))

(defun herdr-api-workspace-rename (label workspace-id)
  "Call the herdr API method `workspace.rename'.

LABEL, WORKSPACE-ID are required.

Return the result alist."
  (herdr-request "workspace.rename"
                 (herdr--params
                  (list (cons 'label label)
                        (cons 'workspace_id workspace-id)))))

(defun herdr-api-workspace-move (insert-index workspace-id)
  "Call the herdr API method `workspace.move'.

INSERT-INDEX, WORKSPACE-ID are required.

Return the result alist."
  (herdr-request "workspace.move"
                 (herdr--params
                  (list (cons 'insert_index insert-index)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-workspace-report-metadata
    (source tokens workspace-id &key seq ttl-ms)
  "Call the herdr API method `workspace.report_metadata'.

SOURCE, TOKENS, WORKSPACE-ID are required.

Keyword arguments: SEQ, TTL-MS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "workspace.report_metadata"
                 (herdr--params
                  (list (cons 'source source) (cons 'tokens tokens)
                        (cons 'workspace_id workspace-id)
                        (cons 'seq seq) (cons 'ttl_ms ttl-ms)))))

(defun herdr-api-workspace-close (workspace-id)
  "Call the herdr API method `workspace.close'.

WORKSPACE-ID is required.

Return the result alist."
  (herdr-request "workspace.close"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-worktree-list (&key cwd workspace-id)
  "Call the herdr API method `worktree.list'.

Keyword arguments: CWD, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "worktree.list"
                 (herdr--params
                  (list (cons 'cwd cwd)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-worktree-create
    (&key base branch cwd focus label path workspace-id)
  "Call the herdr API method `worktree.create'.

Keyword arguments: BASE, BRANCH, CWD, FOCUS, LABEL, PATH, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "worktree.create"
                 (herdr--params
                  (list (cons 'base base) (cons 'branch branch)
                        (cons 'cwd cwd) (cons 'focus focus)
                        (cons 'label label) (cons 'path path)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-worktree-open
    (&key branch cwd focus label path workspace-id)
  "Call the herdr API method `worktree.open'.

Keyword arguments: BRANCH, CWD, FOCUS, LABEL, PATH, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "worktree.open"
                 (herdr--params
                  (list (cons 'branch branch) (cons 'cwd cwd)
                        (cons 'focus focus) (cons 'label label)
                        (cons 'path path)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-worktree-remove (workspace-id &key force)
  "Call the herdr API method `worktree.remove'.

WORKSPACE-ID is required.

Keyword arguments: FORCE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "worktree.remove"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)
                        (cons 'force force)))))

(cl-defun herdr-api-tab-create (&key cwd env focus label workspace-id)
  "Call the herdr API method `tab.create'.

Keyword arguments: CWD, ENV, FOCUS, LABEL, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "tab.create"
                 (herdr--params
                  (list (cons 'cwd cwd) (cons 'env env)
                        (cons 'focus focus) (cons 'label label)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-tab-list (&key workspace-id)
  "Call the herdr API method `tab.list'.

Keyword arguments: WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "tab.list"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)))))

(defun herdr-api-tab-get (tab-id)
  "Call the herdr API method `tab.get'.

TAB-ID is required.

Return the result alist."
  (herdr-request "tab.get"
                 (herdr--params (list (cons 'tab_id tab-id)))))

(defun herdr-api-tab-focus (tab-id)
  "Call the herdr API method `tab.focus'.

TAB-ID is required.

Return the result alist."
  (herdr-request "tab.focus"
                 (herdr--params (list (cons 'tab_id tab-id)))))

(defun herdr-api-tab-rename (label tab-id)
  "Call the herdr API method `tab.rename'.

LABEL, TAB-ID are required.

Return the result alist."
  (herdr-request "tab.rename"
                 (herdr--params
                  (list (cons 'label label) (cons 'tab_id tab-id)))))

(defun herdr-api-tab-move (insert-index tab-id)
  "Call the herdr API method `tab.move'.

INSERT-INDEX, TAB-ID are required.

Return the result alist."
  (herdr-request "tab.move"
                 (herdr--params
                  (list (cons 'insert_index insert-index)
                        (cons 'tab_id tab-id)))))

(defun herdr-api-tab-close (tab-id)
  "Call the herdr API method `tab.close'.

TAB-ID is required.

Return the result alist."
  (herdr-request "tab.close"
                 (herdr--params (list (cons 'tab_id tab-id)))))

(defun herdr-api-agent-list ()
  "Call the herdr API method `agent.list'.

Return the result alist."
  (herdr-request "agent.list"))

(defun herdr-api-agent-get (target)
  "Call the herdr API method `agent.get'.

TARGET is required.

Return the result alist."
  (herdr-request "agent.get"
                 (herdr--params (list (cons 'target target)))))

(cl-defun herdr-api-agent-read
    (source target &key format lines strip-ansi)
  "Call the herdr API method `agent.read'.

SOURCE, TARGET are required.

Keyword arguments: FORMAT, LINES, STRIP-ANSI.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.read"
                 (herdr--params
                  (list (cons 'source source) (cons 'target target)
                        (cons 'format format) (cons 'lines lines)
                        (cons 'strip_ansi strip-ansi)))))

(defun herdr-api-agent-explain (target)
  "Call the herdr API method `agent.explain'.

TARGET is required.

Return the result alist."
  (herdr-request "agent.explain"
                 (herdr--params (list (cons 'target target)))))

(defun herdr-api-agent-send-keys (keys target)
  "Call the herdr API method `agent.send_keys'.

KEYS, TARGET are required.

Return the result alist."
  (herdr-request "agent.send_keys"
                 (herdr--params
                  (list (cons 'keys keys) (cons 'target target)))))

(cl-defun herdr-api-agent-rename (target &key name)
  "Call the herdr API method `agent.rename'.

TARGET is required.

Keyword arguments: NAME.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.rename"
                 (herdr--params
                  (list (cons 'target target) (cons 'name name)))))

(cl-defun herdr-api-agent-view-set (source &key filter label sort)
  "Call the herdr API method `agent.view.set'.

SOURCE is required.

Keyword arguments: FILTER, LABEL, SORT.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.view.set"
                 (herdr--params
                  (list (cons 'source source) (cons 'filter filter)
                        (cons 'label label) (cons 'sort sort)))))

(cl-defun herdr-api-agent-view-clear (&key source)
  "Call the herdr API method `agent.view.clear'.

Keyword arguments: SOURCE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.view.clear"
                 (herdr--params (list (cons 'source source)))))

(defun herdr-api-agent-focus (target)
  "Call the herdr API method `agent.focus'.

TARGET is required.

Return the result alist."
  (herdr-request "agent.focus"
                 (herdr--params (list (cons 'target target)))))

(cl-defun herdr-api-agent-start
    (kind name pane-id &key args timeout-ms)
  "Call the herdr API method `agent.start'.

KIND, NAME, PANE-ID are required.

Keyword arguments: ARGS, TIMEOUT-MS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.start"
                 (herdr--params
                  (list (cons 'kind kind) (cons 'name name)
                        (cons 'pane_id pane-id)
                        (cons 'args (and args (vconcat args)))
                        (cons 'timeout_ms timeout-ms)))))

(cl-defun herdr-api-agent-prompt (target text &key wait)
  "Call the herdr API method `agent.prompt'.

TARGET, TEXT are required.

Keyword arguments: WAIT.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.prompt"
                 (herdr--params
                  (list (cons 'target target) (cons 'text text)
                        (cons 'wait wait)))))

(cl-defun herdr-api-agent-wait (target &key timeout-ms until)
  "Call the herdr API method `agent.wait'.

TARGET is required.

Keyword arguments: TIMEOUT-MS, UNTIL.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "agent.wait"
                 (herdr--params
                  (list (cons 'target target)
                        (cons 'timeout_ms timeout-ms)
                        (cons 'until until)))))

(cl-defun herdr-api-pane-split
    (direction &key cwd env focus ratio target-pane-id workspace-id)
  "Call the herdr API method `pane.split'.

DIRECTION is required.

Keyword arguments: CWD, ENV, FOCUS, RATIO, TARGET-PANE-ID, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.split"
                 (herdr--params
                  (list (cons 'direction direction) (cons 'cwd cwd)
                        (cons 'env env) (cons 'focus focus)
                        (cons 'ratio ratio)
                        (cons 'target_pane_id target-pane-id)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-pane-swap
    (&key direction pane-id source-pane-id target-pane-id)
  "Call the herdr API method `pane.swap'.

Keyword arguments: DIRECTION, PANE-ID, SOURCE-PANE-ID, TARGET-PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.swap"
                 (herdr--params
                  (list (cons 'direction direction)
                        (cons 'pane_id pane-id)
                        (cons 'source_pane_id source-pane-id)
                        (cons 'target_pane_id target-pane-id)))))

(cl-defun herdr-api-pane-move (destination pane-id &key focus)
  "Call the herdr API method `pane.move'.

DESTINATION, PANE-ID are required.

Keyword arguments: FOCUS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.move"
                 (herdr--params
                  (list (cons 'destination destination)
                        (cons 'pane_id pane-id) (cons 'focus focus)))))

(cl-defun herdr-api-pane-zoom (&key mode pane-id)
  "Call the herdr API method `pane.zoom'.

Keyword arguments: MODE, PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.zoom"
                 (herdr--params
                  (list (cons 'mode mode) (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-layout (&key pane-id)
  "Call the herdr API method `pane.layout'.

Keyword arguments: PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.layout"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-process-info (&key pane-id)
  "Call the herdr API method `pane.process_info'.

Keyword arguments: PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.process_info"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(cl-defun herdr-api-layout-export (&key pane-id tab-id)
  "Call the herdr API method `layout.export'.

Keyword arguments: PANE-ID, TAB-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "layout.export"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'tab_id tab-id)))))

(cl-defun herdr-api-layout-apply
    (root &key focus tab-id tab-label workspace-id)
  "Call the herdr API method `layout.apply'.

ROOT is required.

Keyword arguments: FOCUS, TAB-ID, TAB-LABEL, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "layout.apply"
                 (herdr--params
                  (list (cons 'root root) (cons 'focus focus)
                        (cons 'tab_id tab-id)
                        (cons 'tab_label tab-label)
                        (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-layout-set-split-ratio
    (path ratio &key pane-id tab-id)
  "Call the herdr API method `layout.set_split_ratio'.

PATH, RATIO are required.

Keyword arguments: PANE-ID, TAB-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "layout.set_split_ratio"
                 (herdr--params
                  (list (cons 'path path) (cons 'ratio ratio)
                        (cons 'pane_id pane-id) (cons 'tab_id tab-id)))))

(cl-defun herdr-api-pane-neighbor (direction &key pane-id)
  "Call the herdr API method `pane.neighbor'.

DIRECTION is required.

Keyword arguments: PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.neighbor"
                 (herdr--params
                  (list (cons 'direction direction)
                        (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-edges (&key pane-id)
  "Call the herdr API method `pane.edges'.

Keyword arguments: PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.edges"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-focus-direction (direction &key pane-id)
  "Call the herdr API method `pane.focus_direction'.

DIRECTION is required.

Keyword arguments: PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.focus_direction"
                 (herdr--params
                  (list (cons 'direction direction)
                        (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-resize (direction &key amount pane-id)
  "Call the herdr API method `pane.resize'.

DIRECTION is required.

Keyword arguments: AMOUNT, PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.resize"
                 (herdr--params
                  (list (cons 'direction direction)
                        (cons 'amount amount) (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-list (&key workspace-id)
  "Call the herdr API method `pane.list'.

Keyword arguments: WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.list"
                 (herdr--params
                  (list (cons 'workspace_id workspace-id)))))

(cl-defun herdr-api-pane-current (&key caller-pane-id)
  "Call the herdr API method `pane.current'.

Keyword arguments: CALLER-PANE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.current"
                 (herdr--params
                  (list (cons 'caller_pane_id caller-pane-id)))))

(defun herdr-api-pane-get (pane-id)
  "Call the herdr API method `pane.get'.

PANE-ID is required.

Return the result alist."
  (herdr-request "pane.get"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(defun herdr-api-pane-focus (pane-id)
  "Call the herdr API method `pane.focus'.

PANE-ID is required.

Return the result alist."
  (herdr-request "pane.focus"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-rename (pane-id &key label)
  "Call the herdr API method `pane.rename'.

PANE-ID is required.

Keyword arguments: LABEL.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.rename"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'label label)))))

(defun herdr-api-pane-send-text (pane-id text)
  "Call the herdr API method `pane.send_text'.

PANE-ID, TEXT are required.

Return the result alist."
  (herdr-request "pane.send_text"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'text text)))))

(defun herdr-api-pane-send-keys (keys pane-id)
  "Call the herdr API method `pane.send_keys'.

KEYS, PANE-ID are required.

Return the result alist."
  (herdr-request "pane.send_keys"
                 (herdr--params
                  (list (cons 'keys keys) (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-send-input (pane-id &key keys text)
  "Call the herdr API method `pane.send_input'.

PANE-ID is required.

Keyword arguments: KEYS, TEXT.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.send_input"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'keys keys)
                        (cons 'text text)))))

(cl-defun herdr-api-pane-read
    (pane-id source &key format lines strip-ansi)
  "Call the herdr API method `pane.read'.

PANE-ID, SOURCE are required.

Keyword arguments: FORMAT, LINES, STRIP-ANSI.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.read"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'source source)
                        (cons 'format format) (cons 'lines lines)
                        (cons 'strip_ansi strip-ansi)))))

(cl-defun herdr-api-pane-graphics-set
    (format image-height image-width pane-id &key data-base64
            placement)
  "Call the herdr API method `pane.graphics.set'.

FORMAT, IMAGE-HEIGHT, IMAGE-WIDTH, PANE-ID are required.

Keyword arguments: DATA-BASE64, PLACEMENT.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.graphics.set"
                 (herdr--params
                  (list (cons 'format format)
                        (cons 'image_height image-height)
                        (cons 'image_width image-width)
                        (cons 'pane_id pane-id)
                        (cons 'data_base64 data-base64)
                        (cons 'placement placement)))))

(defun herdr-api-pane-graphics-clear (pane-id)
  "Call the herdr API method `pane.graphics.clear'.

PANE-ID is required.

Return the result alist."
  (herdr-request "pane.graphics.clear"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(defun herdr-api-pane-graphics-info (pane-id)
  "Call the herdr API method `pane.graphics.info'.

PANE-ID is required.

Return the result alist."
  (herdr-request "pane.graphics.info"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(cl-defun herdr-api-pane-report-agent
    (agent pane-id source state &key agent-session-id
           agent-session-path message seq)
  "Call the herdr API method `pane.report_agent'.

AGENT, PANE-ID, SOURCE, STATE are required.

Keyword arguments: AGENT-SESSION-ID, AGENT-SESSION-PATH, MESSAGE, SEQ.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.report_agent"
                 (herdr--params
                  (list (cons 'agent agent) (cons 'pane_id pane-id)
                        (cons 'source source) (cons 'state state)
                        (cons 'agent_session_id agent-session-id)
                        (cons 'agent_session_path agent-session-path)
                        (cons 'message message) (cons 'seq seq)))))

(cl-defun herdr-api-pane-report-agent-session
    (agent pane-id source &key agent-session-id agent-session-path seq
           session-start-source)
  "Call the herdr API method `pane.report_agent_session'.

AGENT, PANE-ID, SOURCE are required.

Keyword arguments: AGENT-SESSION-ID, AGENT-SESSION-PATH, SEQ,
SESSION-START-SOURCE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.report_agent_session"
                 (herdr--params
                  (list (cons 'agent agent) (cons 'pane_id pane-id)
                        (cons 'source source)
                        (cons 'agent_session_id agent-session-id)
                        (cons 'agent_session_path agent-session-path)
                        (cons 'seq seq)
                        (cons 'session_start_source
                              session-start-source)))))

(cl-defun herdr-api-pane-report-metadata
    (pane-id source &key agent applies-to-source clear-display-agent
             clear-state-labels clear-title display-agent seq
             state-labels title tokens ttl-ms)
  "Call the herdr API method `pane.report_metadata'.

PANE-ID, SOURCE are required.

Keyword arguments: AGENT, APPLIES-TO-SOURCE, CLEAR-DISPLAY-AGENT,
CLEAR-STATE-LABELS, CLEAR-TITLE, DISPLAY-AGENT, SEQ, STATE-LABELS,
TITLE, TOKENS, TTL-MS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.report_metadata"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'source source)
                        (cons 'agent agent)
                        (cons 'applies_to_source applies-to-source)
                        (cons 'clear_display_agent clear-display-agent)
                        (cons 'clear_state_labels clear-state-labels)
                        (cons 'clear_title clear-title)
                        (cons 'display_agent display-agent)
                        (cons 'seq seq)
                        (cons 'state_labels state-labels)
                        (cons 'title title) (cons 'tokens tokens)
                        (cons 'ttl_ms ttl-ms)))))

(cl-defun herdr-api-pane-clear-agent-authority
    (pane-id &key seq source)
  "Call the herdr API method `pane.clear_agent_authority'.

PANE-ID is required.

Keyword arguments: SEQ, SOURCE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.clear_agent_authority"
                 (herdr--params
                  (list (cons 'pane_id pane-id) (cons 'seq seq)
                        (cons 'source source)))))

(cl-defun herdr-api-pane-release-agent (agent pane-id source &key seq)
  "Call the herdr API method `pane.release_agent'.

AGENT, PANE-ID, SOURCE are required.

Keyword arguments: SEQ.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.release_agent"
                 (herdr--params
                  (list (cons 'agent agent) (cons 'pane_id pane-id)
                        (cons 'source source) (cons 'seq seq)))))

(defun herdr-api-pane-close (pane-id)
  "Call the herdr API method `pane.close'.

PANE-ID is required.

Return the result alist."
  (herdr-request "pane.close"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(defun herdr-api-popup-close ()
  "Call the herdr API method `popup.close'.

Return the result alist."
  (herdr-request "popup.close"))

(defun herdr-api-events-subscribe (subscriptions)
  "Call the herdr API method `events.subscribe'.

SUBSCRIPTIONS is required.

Only the acknowledgement is returned; use `herdr-subscribe' to
receive the events that follow.

Return the result alist."
  (herdr-request "events.subscribe"
                 (herdr--params
                  (list (cons 'subscriptions subscriptions)))))

(cl-defun herdr-api-events-wait (match-event &key timeout-ms)
  "Call the herdr API method `events.wait'.

MATCH-EVENT is required.

Keyword arguments: TIMEOUT-MS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "events.wait"
                 (herdr--params
                  (list (cons 'match_event match-event)
                        (cons 'timeout_ms timeout-ms)))))

(cl-defun herdr-api-pane-wait-for-output
    (match pane-id source &key lines strip-ansi timeout-ms)
  "Call the herdr API method `pane.wait_for_output'.

MATCH, PANE-ID, SOURCE are required.

Keyword arguments: LINES, STRIP-ANSI, TIMEOUT-MS.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "pane.wait_for_output"
                 (herdr--params
                  (list (cons 'match match) (cons 'pane_id pane-id)
                        (cons 'source source) (cons 'lines lines)
                        (cons 'strip_ansi strip-ansi)
                        (cons 'timeout_ms timeout-ms)))))

(defun herdr-api-integration-install (target)
  "Call the herdr API method `integration.install'.

TARGET is required.

Return the result alist."
  (herdr-request "integration.install"
                 (herdr--params (list (cons 'target target)))))

(defun herdr-api-integration-uninstall (target)
  "Call the herdr API method `integration.uninstall'.

TARGET is required.

Return the result alist."
  (herdr-request "integration.uninstall"
                 (herdr--params (list (cons 'target target)))))

(cl-defun herdr-api-plugin-link (path &key enabled source)
  "Call the herdr API method `plugin.link'.

PATH is required.

Keyword arguments: ENABLED, SOURCE.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.link"
                 (herdr--params
                  (list (cons 'path path) (cons 'enabled enabled)
                        (cons 'source source)))))

(cl-defun herdr-api-plugin-list (&key plugin-id)
  "Call the herdr API method `plugin.list'.

Keyword arguments: PLUGIN-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.list"
                 (herdr--params (list (cons 'plugin_id plugin-id)))))

(defun herdr-api-plugin-unlink (plugin-id)
  "Call the herdr API method `plugin.unlink'.

PLUGIN-ID is required.

Return the result alist."
  (herdr-request "plugin.unlink"
                 (herdr--params (list (cons 'plugin_id plugin-id)))))

(defun herdr-api-plugin-enable (plugin-id)
  "Call the herdr API method `plugin.enable'.

PLUGIN-ID is required.

Return the result alist."
  (herdr-request "plugin.enable"
                 (herdr--params (list (cons 'plugin_id plugin-id)))))

(defun herdr-api-plugin-disable (plugin-id)
  "Call the herdr API method `plugin.disable'.

PLUGIN-ID is required.

Return the result alist."
  (herdr-request "plugin.disable"
                 (herdr--params (list (cons 'plugin_id plugin-id)))))

(cl-defun herdr-api-plugin-action-list (&key plugin-id)
  "Call the herdr API method `plugin.action.list'.

Keyword arguments: PLUGIN-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.action.list"
                 (herdr--params (list (cons 'plugin_id plugin-id)))))

(cl-defun herdr-api-plugin-action-invoke
    (action-id &key context plugin-id)
  "Call the herdr API method `plugin.action.invoke'.

ACTION-ID is required.

Keyword arguments: CONTEXT, PLUGIN-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.action.invoke"
                 (herdr--params
                  (list (cons 'action_id action-id)
                        (cons 'context context)
                        (cons 'plugin_id plugin-id)))))

(cl-defun herdr-api-plugin-log-list (&key limit plugin-id)
  "Call the herdr API method `plugin.log.list'.

Keyword arguments: LIMIT, PLUGIN-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.log.list"
                 (herdr--params
                  (list (cons 'limit limit)
                        (cons 'plugin_id plugin-id)))))

(cl-defun herdr-api-plugin-pane-open
    (entrypoint plugin-id &key cwd direction env focus height
                placement target-pane-id width workspace-id)
  "Call the herdr API method `plugin.pane.open'.

ENTRYPOINT, PLUGIN-ID are required.

Keyword arguments: CWD, DIRECTION, ENV, FOCUS, HEIGHT, PLACEMENT,
TARGET-PANE-ID, WIDTH, WORKSPACE-ID.
Omitted (nil) keys are left out of the request;
pass `:false' to send a literal false.

Return the result alist."
  (herdr-request "plugin.pane.open"
                 (herdr--params
                  (list (cons 'entrypoint entrypoint)
                        (cons 'plugin_id plugin-id) (cons 'cwd cwd)
                        (cons 'direction direction) (cons 'env env)
                        (cons 'focus focus) (cons 'height height)
                        (cons 'placement placement)
                        (cons 'target_pane_id target-pane-id)
                        (cons 'width width)
                        (cons 'workspace_id workspace-id)))))

(defun herdr-api-plugin-pane-focus (pane-id)
  "Call the herdr API method `plugin.pane.focus'.

PANE-ID is required.

Return the result alist."
  (herdr-request "plugin.pane.focus"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(defun herdr-api-plugin-pane-close (pane-id)
  "Call the herdr API method `plugin.pane.close'.

PANE-ID is required.

Return the result alist."
  (herdr-request "plugin.pane.close"
                 (herdr--params (list (cons 'pane_id pane-id)))))

(provide 'herdr-api)
;;; herdr-api.el ends here
